!     #########
      SUBROUTINE ALLOC_TRIP_DIAG_STATE (TPDG,KSTATE)
!     #######################################################################
!
!!****  *ALLOC_TRIP_DIAG_STATE*
!!
!!    PURPOSE
!!    -------
!
!     Allocate diagnostic variables in the state space
!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      S. Munier
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    07/2019
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
!
!
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_t
!
USE MODN_TRIP,       ONLY : CGROUNDW, CVIT, LFLOOD
USE MODN_TRIP_RUN,   ONLY : LDIAG_MISC
USE MODD_TRIP_OASIS, ONLY : LCPL_LAND, LCPL_FLOOD
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
!*      0.1    declarations of arguments
!
TYPE(TRIP_DIAG_t), INTENT(INOUT) :: TPDG
!
INTEGER, INTENT(IN)          :: KSTATE
!
!*      0.2    declarations of output variables
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('ALLOC_TRIP_DIAG_STATE',0,ZHOOK_HANDLE)
!
! * Allocate and initialyse diagnostic variables
!
ALLOCATE(TPDG%TDIAG_ST%XSURF_STO(KSTATE))
ALLOCATE(TPDG%TDIAG_ST%XQDIS    (KSTATE))
TPDG%TDIAG_ST%XSURF_STO(:) = 0.0
TPDG%TDIAG_ST%XQDIS    (:) = 0.0

IF(LDIAG_MISC)THEN
  ALLOCATE(TPDG%TDIAG_ST%XQIN     (KSTATE))
  TPDG%TDIAG_ST%XQIN      (:) = 0.0
ELSE
  ALLOCATE(TPDG%TDIAG_ST%XQIN(0))
ENDIF
!
IF(LCPL_LAND.AND.LDIAG_MISC)THEN
  ALLOCATE(TPDG%TDIAG_ST%XRUNOFF(KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XDRAIN (KSTATE))
  TPDG%TDIAG_ST%XRUNOFF(:) = 0.0
  TPDG%TDIAG_ST%XDRAIN (:) = 0.0
ELSE
  ALLOCATE(TPDG%TDIAG_ST%XRUNOFF(0))
  ALLOCATE(TPDG%TDIAG_ST%XDRAIN (0))
ENDIF

IF(CGROUNDW/='DEF')THEN
  ALLOCATE(TPDG%TDIAG_ST%XGROUND_STO (KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XQGF        (KSTATE))
  TPDG%TDIAG_ST%XGROUND_STO (:) = 0.0
  TPDG%TDIAG_ST%XQGF        (:) = 0.0
ELSE
  ALLOCATE(TPDG%TDIAG_ST%XGROUND_STO(0))
  ALLOCATE(TPDG%TDIAG_ST%XQGF       (0))
ENDIF

IF(CGROUNDW=='DIF')THEN
!
  ALLOCATE(TPDG%TDIAG_ST%XHGROUND(KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XFWTD   (KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XWTD    (KSTATE))
  TPDG%TDIAG_ST%XHGROUND(:) = 0.0
  TPDG%TDIAG_ST%XFWTD   (:) = 0.0
  TPDG%TDIAG_ST%XWTD    (:) = 0.0
!
  IF(LDIAG_MISC)THEN
    ALLOCATE(TPDG%TDIAG_ST%XQGCELL (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XHGHS   (KSTATE))
    TPDG%TDIAG_ST%XQGCELL (:) = 0.0
    TPDG%TDIAG_ST%XHGHS   (:) = 0.0
  ELSE
    ALLOCATE(TPDG%TDIAG_ST%XQGCELL (0))
    ALLOCATE(TPDG%TDIAG_ST%XHGHS   (0))
  ENDIF
!
ELSE
  ALLOCATE(TPDG%TDIAG_ST%XFWTD   (0))
  ALLOCATE(TPDG%TDIAG_ST%XWTD    (0))
  ALLOCATE(TPDG%TDIAG_ST%XHGROUND(0))
  ALLOCATE(TPDG%TDIAG_ST%XQGCELL (0))
  ALLOCATE(TPDG%TDIAG_ST%XHGHS   (0))
ENDIF
!
IF(CVIT=='VAR')THEN
  ALLOCATE(TPDG%TDIAG_ST%XHS (KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XVEL(KSTATE))
  TPDG%TDIAG_ST%XHS (:) = 0.0
  TPDG%TDIAG_ST%XVEL(:) = 0.0
ELSE
  ALLOCATE(TPDG%TDIAG_ST%XHS (0))
  ALLOCATE(TPDG%TDIAG_ST%XVEL(0))
ENDIF
!
IF ((LFLOOD.OR.LCPL_FLOOD).AND.LDIAG_MISC) THEN
   ALLOCATE(TPDG%TDIAG_ST%XSOURCE(KSTATE))
   TPDG%TDIAG_ST%XSOURCE(:) = 0.0
ELSE
   ALLOCATE(TPDG%TDIAG_ST%XSOURCE(0))
ENDIF
!
IF(LFLOOD)THEN
  ALLOCATE(TPDG%TDIAG_ST%XFLOOD_STO (KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XFF        (KSTATE))
  ALLOCATE(TPDG%TDIAG_ST%XHF        (KSTATE))
  TPDG%TDIAG_ST%XFLOOD_STO (:) = 0.0
  TPDG%TDIAG_ST%XFF        (:) = 0.0
  TPDG%TDIAG_ST%XHF        (:) = 0.0
  IF(LDIAG_MISC)THEN
    ALLOCATE(TPDG%TDIAG_ST%XQFR   (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XQRF   (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XVFIN  (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XVFOUT (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XWF    (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XLF    (KSTATE))
    ALLOCATE(TPDG%TDIAG_ST%XHSF   (KSTATE))
    TPDG%TDIAG_ST%XQFR   (:) = 0.0
    TPDG%TDIAG_ST%XQRF   (:) = 0.0
    TPDG%TDIAG_ST%XVFIN  (:) = 0.0
    TPDG%TDIAG_ST%XVFOUT (:) = 0.0
    TPDG%TDIAG_ST%XWF    (:) = 0.0
    TPDG%TDIAG_ST%XLF    (:) = 0.0
    TPDG%TDIAG_ST%XHSF   (:) = 0.0
  ELSE
    ALLOCATE(TPDG%TDIAG_ST%XQFR   (0))
    ALLOCATE(TPDG%TDIAG_ST%XQRF   (0))
    ALLOCATE(TPDG%TDIAG_ST%XVFIN  (0))
    ALLOCATE(TPDG%TDIAG_ST%XVFOUT (0))
    ALLOCATE(TPDG%TDIAG_ST%XWF    (0))
    ALLOCATE(TPDG%TDIAG_ST%XLF    (0))
    ALLOCATE(TPDG%TDIAG_ST%XHSF   (0))
  ENDIF
ELSE
  ALLOCATE(TPDG%TDIAG_ST%XFLOOD_STO (0))
  ALLOCATE(TPDG%TDIAG_ST%XHF        (0))
  ALLOCATE(TPDG%TDIAG_ST%XFF        (0))
  ALLOCATE(TPDG%TDIAG_ST%XQFR       (0))
  ALLOCATE(TPDG%TDIAG_ST%XQRF       (0))
  ALLOCATE(TPDG%TDIAG_ST%XVFIN      (0))
  ALLOCATE(TPDG%TDIAG_ST%XVFOUT     (0))
  ALLOCATE(TPDG%TDIAG_ST%XWF        (0))
  ALLOCATE(TPDG%TDIAG_ST%XLF        (0))
  ALLOCATE(TPDG%TDIAG_ST%XHSF       (0))
ENDIF
!
IF (LHOOK) CALL DR_HOOK('ALLOC_TRIP_DIAG_STATE',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
END SUBROUTINE ALLOC_TRIP_DIAG_STATE
