SUBROUTINE ASSIM_ETKF_LOCAL(TPST, TPA, KENS, KPNT, KOBS, PXB, POBS, POBS_ERR, KDTOBS, PHX, PXA)
!####################################################################
!
!!****  *ASSIM_ETKF_LOCAL*
!!
!!    PURPOSE
!!    -------
!!      Ensemble Kalman computation with localization
!!
!!    AUTHOR
!!    ------
!!      S. Munier   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!
!-------------------------------------------------------------------------------
!
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
USE MODD_TRIP_ANALYSIS, ONLY : TRIP_ANALYSIS_t
!
USE MODD_TRIP_PAR, ONLY : XUNDEF
USE MODD_TRIP_ASSIM
!
USE MODN_TRIP_ASSIM
USE MODI_ASSIM_BUILD_YO_HX
USE MODI_ASSIM_LOCALIZATION
USE MODI_ASSIM_INFLATE_FIELD
USE MODI_ASSIM_INVERSE
USE MODI_TEST_DIAG_WRITE
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
INCLUDE 'mpif.h'
!
!* 0.1    declarations of arguments
!
TYPE(TRIP_STATE_t),    INTENT(INOUT) :: TPST
TYPE(TRIP_ANALYSIS_t), INTENT(INOUT) :: TPA
!
INTEGER,                 INTENT(IN)    :: KENS
INTEGER,                 INTENT(IN)    :: KPNT
INTEGER,                 INTENT(IN)    :: KOBS
REAL,    DIMENSION(:,:), INTENT(IN)    :: PXB
REAL,    DIMENSION(:),   INTENT(IN)    :: POBS
REAL,    DIMENSION(:),   INTENT(IN)    :: POBS_ERR
INTEGER, DIMENSION(:),   INTENT(IN)    :: KDTOBS
REAL,    DIMENSION(:,:), INTENT(INOUT) :: PHX
REAL,    DIMENSION(:,:), INTENT(OUT)   :: PXA
!
!* 0.2    declarations of local variables
!
REAL, DIMENSION(KOBS,KENS) :: ZHX
REAL, DIMENSION(KOBS)      :: ZD
REAL, DIMENSION(KPNT)      :: ZXB_MEAN
REAL, DIMENSION(KOBS)      :: ZHX_MEAN
REAL, DIMENSION(KOBS)      :: ZSIGMA_R
!
INTEGER, DIMENSION(:),ALLOCATABLE :: IOBS_STATE
REAL, DIMENSION(:),   ALLOCATABLE :: ZYO
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLOCAL
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLOCAL_RED
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLOCAL_PROC
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE_RED
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE_PROC
REAL, DIMENSION(:,:), ALLOCATABLE :: ZXA_PROC
REAL, DIMENSION(:,:), ALLOCATABLE :: ZC_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZPA_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWA_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWA_L_MEAN
REAL, DIMENSION(:,:), ALLOCATABLE :: ZD_L
REAL, DIMENSION(:),   ALLOCATABLE :: ZR_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZN_L
REAL, DIMENSION(:),   ALLOCATABLE :: ZS
REAL, DIMENSION(:,:), ALLOCATABLE :: ZU
!
REAL, DIMENSION(:),   ALLOCATABLE :: ZMASK
REAL, DIMENSION(:),   ALLOCATABLE :: ZDUM
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWORK
!
INTEGER :: ISEED, IERR, IDUM
INTEGER :: I, J, K, IOBS, IOBS_L
INTEGER :: IPNT_PROC, ISTART, ISTOP
LOGICAL :: GWRITE
!
INTEGER :: INB_PNT
INTEGER, DIMENSION(:), ALLOCATABLE :: IID_PNT
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('ASSIM_ETKF_LOCAL',0,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
!
  ALLOCATE(IOBS_STATE(KOBS))
  ALLOCATE(ZE(KPNT,KENS))
  ALLOCATE(ZYO(KOBS))
  ALLOCATE(ZLOCAL(KPNT,KOBS))
!
! Build observation vector and model equivalent of obs
!
  CALL ASSIM_BUILD_YO_HX(TPST, KENS, KOBS, KPNT, IOBS_STATE, POBS, PXB, ZYO, ZHX)
!
  DO I = 1,KOBS
    IF (KDTOBS(IOBS_STATE(I))==0) THEN
      PHX(IOBS_STATE(I),:) = ZHX(I,:)
    ELSE
      ZHX(I,:) = PHX(IOBS_STATE(I),:)
    ENDIF
  ENDDO
!
! Localization
!
  CALL ASSIM_LOCALIZATION(KOBS, KPNT, TPST%NNEXTST, TPST%NPREVST, KDTOBS, IOBS_STATE, ZLOCAL)
!
! Build mean background state and mean model equivalent of obs
!
  ZXB_MEAN(:) = 0.
  ZHX_MEAN(:) = 0.
  DO I = 1, KENS
    ZXB_MEAN(:) = ZXB_MEAN(:) + PXB(:,I)
    ZHX_MEAN(:) = ZHX_MEAN(:) + ZHX(:,I)
  ENDDO
  ZXB_MEAN(:) = ZXB_MEAN(:)/REAL(KENS)
  ZHX_MEAN(:) = ZHX_MEAN(:)/REAL(KENS)
!
  DO I = 1, KENS
    ZE(:,I) = PXB(:,I)-ZXB_MEAN(:)
    ZHX(:,I) = ZHX(:,I)-ZHX_MEAN(:)
  ENDDO
!
! Domain reduction
!
  INB_PNT = 0
  ALLOCATE(IID_PNT(KPNT))
  DO I = 1,KPNT
    IF (SUM(ZLOCAL(I,:))>0) THEN
      INB_PNT = INB_PNT+1
      IID_PNT(INB_PNT) = I
    ENDIF
  ENDDO
  IPNT_PROC = CEILING(INB_PNT*1./NPROC_ASSIM)
  ALLOCATE(ZLOCAL_RED(KOBS,IPNT_PROC*NPROC_ASSIM))
  ALLOCATE(ZE_RED(KENS,IPNT_PROC*NPROC_ASSIM))
  ZLOCAL_RED(:,:) = 0.
  ZE_RED(:,:) = 0.
  DO I = 1,INB_PNT
    ZLOCAL_RED(:,I) = ZLOCAL(IID_PNT(I),:)
    ZE_RED(:,I) = ZE(IID_PNT(I),:)
  ENDDO
!
! Innovation
!
  ZD(:) = ZYO(:) - ZHX_MEAN(:)
  DO I = 1, KOBS
    IF (LUSE_OBS_ERR) THEN
      ZSIGMA_R(I) = MAX(POBS_ERR(IOBS_STATE(I)),1E-6)
    ELSE
      IF (CHQ .EQ.'DIS') ZSIGMA_R(I) = MAX(XSIGMA_R*ZYO(I),0.1)
      IF (CHQ .EQ.'HST') ZSIGMA_R(I) = XSIGMA_R
      IF (CHQ .EQ.'HAN') ZSIGMA_R(I) = XSIGMA_R
    ENDIF
  ENDDO
!
! Apply inflation (as in Anderson, 2009 and Gharamti, 2018)
!
  IF (CINFL/='DEF') CALL INFLATE_STATE(TPA,INB_PNT,KENS,KOBS,IID_PNT,ZXB_MEAN,ZHX,ZD,ZLOCAL_RED,ZSIGMA_R,ZE_RED)
!
! Write localization matrix in diag
!
  CALL TEST_DIAG_WRITE('LOCAL',GWRITE)
  IF (GWRITE) THEN
    TPA%XLOCAL(:,:) = XUNDEF
    DO I = 1,KOBS
      TPA%XLOCAL(:,IOBS_STATE(I)) = ZLOCAL(:,I)
    ENDDO
  ENDIF
!
  DEALLOCATE(ZE)
  DEALLOCATE(ZYO)
  DEALLOCATE(ZLOCAL)
!
ENDIF
!
! Serialization
!
CALL MPI_BCAST(INB_PNT, 1, MPI_INTEGER, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(IPNT_PROC, 1, MPI_INTEGER, NPIO_ASSIM, NCOMM_ASSIM, IERR)
!
ALLOCATE(ZE_PROC(KENS,IPNT_PROC))
ALLOCATE(ZLOCAL_PROC(KOBS,IPNT_PROC))
!
CALL MPI_BCAST(ZHX_MEAN, KOBS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(ZHX, KOBS*KENS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(ZD, KOBS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(ZSIGMA_R, KOBS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_SCATTER(ZE_RED, KENS*IPNT_PROC, MPI_DOUBLE, ZE_PROC, KENS*IPNT_PROC, MPI_DOUBLE, &
                 NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_SCATTER(ZLOCAL_RED, KOBS*IPNT_PROC, MPI_DOUBLE, ZLOCAL_PROC, KOBS*IPNT_PROC, MPI_DOUBLE, &
                 NPIO_ASSIM, NCOMM_ASSIM, IERR)
!
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
  DEALLOCATE(ZE_RED)
  DEALLOCATE(ZLOCAL_RED)
ENDIF
!
ISTART = NRANK_ASSIM*IPNT_PROC+1
ISTOP  = MIN((NRANK_ASSIM+1)*IPNT_PROC,INB_PNT)
!
ALLOCATE(ZXA_PROC(KENS,IPNT_PROC))
ZXA_PROC(:,:) = 0.
!
! LOCAL KALMAN
!
ALLOCATE(ZE_L(1,KENS))
ALLOCATE(ZPA_L(KENS,KENS))
ALLOCATE(ZWA_L(KENS,KENS))
ALLOCATE(ZWA_L_MEAN(KENS,1))
ALLOCATE(ZS(KENS))
ALLOCATE(ZU(KENS,KENS))
!
DO I = 1,ISTOP-ISTART+1
  !
  IOBS_L = 0
  DO J = 1,KOBS
    IF (ZLOCAL_PROC(J,I)>0) IOBS_L = IOBS_L+1
  ENDDO
  IF (IOBS_L==0) CYCLE
  !
  ALLOCATE(ZR_L(IOBS_L))
  ALLOCATE(ZN_L(IOBS_L,KENS))
  ALLOCATE(ZD_L(IOBS_L,1))
  ALLOCATE(ZC_L(KENS,IOBS_L))
  !
  IOBS = 0
  DO J = 1,KOBS
    IF (ZLOCAL_PROC(J,I)>0) THEN
      IOBS = IOBS+1
      ZR_L(IOBS) = ZSIGMA_R(J)*ZSIGMA_R(J)
      ZN_L(IOBS,:) = ZHX(J,:)
      ZD_L(IOBS,1) = ZD(J) * ZLOCAL_PROC(J,I)
    ENDIF
  ENDDO
  ZE_L(1,:) = ZE_PROC(:,I)
  !
  ! ZC = ZHX^t*inv(R)
  DO IOBS = 1,IOBS_L
    ZC_L(:,IOBS) = ZN_L(IOBS,:) / ZR_L(IOBS)
  ENDDO
  !
  ! ZPA = inv((KENS-1)*ZIDENTITY/XAMP_I + ZC*ZN)
  !
  ZU(:,:) = 0.
  DO K = 1,KENS
    ZU(K,K) = (KENS-1) ! /XAMP_I
  ENDDO
  ZU(:,:) = ZU(:,:) + MATMUL(ZC_L,ZN_L)
  !
  IDUM = 3*KENS-1
  ALLOCATE(ZDUM(IDUM))
  CALL DSYEV('V','U',KENS,ZU,KENS,ZS,ZDUM,IDUM,IERR)
  DEALLOCATE(ZDUM)
  !
  ALLOCATE(ZWORK(KENS,KENS))
  ZWORK(:,:) = 0.
  DO K = 1,KENS
    ZWORK(K,K) = 1./MAX(ZS(K),1E-6)
  ENDDO
  ZPA_L = MATMUL(ZU,MATMUL(ZWORK,TRANSPOSE(ZU)))
  !
  ! ZWA = ((KENS-1)*ZPA)^0.5
  DO K = 1,KENS
    ZWORK(K,K) = SQRT(ZWORK(K,K))
  ENDDO
  ZWA_L = SQRT(REAL(KENS-1))*MATMUL(ZU,MATMUL(ZWORK,TRANSPOSE(ZU)))
  DEALLOCATE(ZWORK)
  !
  ! ZWA_MEAN = ZPA * ( ZC*(ZYO-ZHX_MEAN) )
  ZWA_L_MEAN = MATMUL(ZPA_L,MATMUL(ZC_L,ZD_L))
  !
  ! ZWA(:,:) = ZWA(:,:)+ZWA_MEAN(:)
  DO K = 1,KENS
    ZWA_L(:,K) = ZWA_L(:,K)+ZWA_L_MEAN(:,1)
  ENDDO
  !
  ! ZXA(:,I) = ZXB(:,:)*ZWA(:,I) + ZXB_MEAN(:)
  ALLOCATE(ZWORK(1,KENS))
  ZWORK = MATMUL(ZE_L,ZWA_L)
  ZXA_PROC(:,I) = ZWORK(1,:)
  DEALLOCATE(ZWORK)
  !
  DEALLOCATE(ZR_L)
  DEALLOCATE(ZN_L)
  DEALLOCATE(ZD_L)
  DEALLOCATE(ZC_L)
  !
ENDDO
!
DEALLOCATE(ZE_L)
DEALLOCATE(ZPA_L)
DEALLOCATE(ZWA_L)
DEALLOCATE(ZWA_L_MEAN)
DEALLOCATE(ZS)
DEALLOCATE(ZU)
!
! Gathering
!
IF (NRANK_ASSIM==NPIO_ASSIM) ALLOCATE(ZWORK(KENS,IPNT_PROC*NPROC_ASSIM))
CALL MPI_GATHER(ZXA_PROC,IPNT_PROC*KENS,MPI_DOUBLE,ZWORK,IPNT_PROC*KENS,MPI_DOUBLE, &
                NPIO_ASSIM,NCOMM_ASSIM,IERR)
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
  PXA(:,:) = PXB(:,:)
  DO I = 1,INB_PNT
    PXA(IID_PNT(I),:) = ZXB_MEAN(IID_PNT(I))+ZWORK(:,I)
  ENDDO
  DEALLOCATE(ZWORK)
  DEALLOCATE(IID_PNT)
ENDIF
!
DEALLOCATE(ZXA_PROC)
DEALLOCATE(ZLOCAL_PROC)
DEALLOCATE(ZE_PROC)
!
! Update
!
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
!
  TPA%XB(:,:) = PXB(:,:)
  TPA%XA(:,:) = PXA(:,:)
  TPA%XINNOV(:) = XUNDEF
  DO I = 1,KOBS
    TPA%XINNOV(IOBS_STATE(I)) = ZD(I)
  ENDDO
!
  DEALLOCATE(IOBS_STATE)
!
ENDIF
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('ASSIM_ETKF_LOCAL',1,ZHOOK_HANDLE)
!
CONTAINS
!
SUBROUTINE INFLATE_STATE(TPA,INB_PNT,KENS,KOBS,IID_PNT,ZXB_MEAN,ZHX,ZD,ZLOCAL_RED,ZSIGMA_R,ZE_RED)
!
IMPLICIT NONE
!
TYPE(TRIP_ANALYSIS_t), INTENT(INOUT) :: TPA
!
INTEGER,               INTENT(IN)    :: INB_PNT, KENS, KOBS
INTEGER, DIMENSION(:), INTENT(IN)    :: IID_PNT
REAL, DIMENSION(:),    INTENT(IN)    :: ZXB_MEAN
REAL, DIMENSION(:,:),  INTENT(IN)    :: ZHX
REAL, DIMENSION(:),    INTENT(IN)    :: ZD
REAL, DIMENSION(:,:),  INTENT(IN)    :: ZLOCAL_RED
REAL, DIMENSION(:),    INTENT(IN)    :: ZSIGMA_R
REAL, DIMENSION(:,:),  INTENT(INOUT) :: ZE_RED
!
INTEGER :: I, J, K
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLAMBDA, ZLAMBDA_VAR
REAL, DIMENSION(:),   ALLOCATABLE :: ZE_VAR
REAL :: ZHX_VAR, ZCOV, ZR, ZGAMMA, ZLAMBDA0, ZLAMBDAP_MEAN, ZTHETA
REAL :: ZLBAR, ZDTHETA_DLAMBDA, ZLPRIME, ZA, ZB, ZC, ZDISCR, ZLAMBDA1, ZLAMBDA2
REAL :: ZALPHA, ZBETA, ZLAM, ZSIG, ZRATIO, ZGAMMA_RATIO
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ASSIM_ETKF_LOCAL:INFLATE_STATE',0,ZHOOK_HANDLE)
!
! 2. Compute background variance
ALLOCATE(ZLAMBDA(INB_PNT,KOBS))
ALLOCATE(ZLAMBDA_VAR(INB_PNT,KOBS))
ALLOCATE(ZE_VAR(INB_PNT))
ZLAMBDA(:,:) = 0.
ZLAMBDA_VAR(:,:) = 0.
ZE_VAR(:) = 0.
DO J = 1,KENS
  ZE_VAR(:) = ZE_VAR(:)+ZE_RED(J,:)**2/(KENS-1)
ENDDO
!
IF (CINFL=='IMP') THEN
  DO I = 1,INB_PNT
    ZLAMBDA(I,1) = (1+((XAMP_I-1)*ZXB_MEAN(IID_PNT(I)))**2/ZE_VAR(I))
  ENDDO
ELSE
!
! 3. For each observation
DO I = 1,KOBS
  ! a. Compute ZHX
  ! b. Compte ZHX_MEAN, ZHX_VAR and ZD
  ZHX_VAR = 0.
  DO J = 1,KENS
    ZHX_VAR = ZHX_VAR+ZHX(I,J)**2/(KENS-1)
  ENDDO
  ! c. For each state
  DO J = 1,INB_PNT
    IF (ZLOCAL_RED(I,J)<=0) CYCLE
    ZLAMBDA(J,I) = TPA%XINFL(IID_PNT(J))
    ZLAMBDA_VAR(J,I) = TPA%XINFL_VAR(IID_PNT(J))
    ! c1. Compute sample correlation between ZHX and ZXB
    ZCOV = 0.
    DO K = 1,KENS
      ZCOV = ZCOV+ZE_RED(K,I)*ZHX(I,K)/(KENS-1)
    ENDDO
    ZR = ZCOV/SQRT(ZE_VAR(J)*ZHX_VAR)
    ! c2. Compute localization factors
    ! ZLOCAL_RED(I,J)
    ! c3. Compute ZGAMMA and ZLAMBDA0
    ZGAMMA = ZLOCAL_RED(I,J) * ZR
    ZLAMBDAP_MEAN = ZLAMBDA(J,I)
    ZLAMBDA0 = (1+ZGAMMA*(SQRT(ZLAMBDAP_MEAN)-1))**2
    !
    IF (CINFL=='A09') THEN ! Gaussian method from Anderson (2009)
      ! c4. Compute ZTHETA using ZLAMBDA0 (Eq. 26 in Gharamti, 2018)
      ZTHETA = SQRT(ZLAMBDA0*ZHX_VAR+ZSIGMA_R(I)**2)
      ! c5. Compute updated value for the mean of ZLAMBDA corresponding to this state
      ZLBAR = 1/(SQRT(2*3.1415)*ZTHETA)*EXP(-0.5*(ZD(I)/ZTHETA)**2)
      ZDTHETA_DLAMBDA = 0.5*ZHX_VAR*ZGAMMA*(1-ZGAMMA+ZGAMMA*SQRT(ZLAMBDAP_MEAN))/(ZTHETA*SQRT(ZLAMBDAP_MEAN))
      ZLPRIME = ZLBAR*((ZD(I)/ZTHETA)**2-1)/ZTHETA*ZDTHETA_DLAMBDA
      ZB = ZLBAR/ZLPRIME-2*ZLAMBDAP_MEAN
      ZC = ZLAMBDAP_MEAN**2-ZLAMBDA_VAR(J,I)-ZLBAR*ZLAMBDAP_MEAN/ZLPRIME
      ZDISCR = ZB**2-4*ZC
      ZLAMBDA1 = 0.5*(-ZB-SQRT(ZDISCR))
      ZLAMBDA2 = 0.5*(-ZB+SQRT(ZDISCR))
      IF (ABS(ZLAMBDA1-ZLAMBDAP_MEAN)>ABS(ZLAMBDA2-ZLAMBDAP_MEAN)) ZLAMBDA1 = ZLAMBDA2
      ! c6. Compute updated value for the variance of ZLAMBDA (or keep variance constant)
      ZRATIO = -(2*(ZLAMBDA1-ZLAMBDA(J,I))/ZLAMBDA_VAR(J,I)+1)
      ZLAMBDA(J,I) = ZLAMBDA1
      ZLAMBDA_VAR(J,I) = -ZLAMBDA_VAR(J,I)/ZRATIO
    ELSEIF(CINFL=='S21') THEN ! Inverse gamma method from Gharamti (2018) and adapted in Su et al. (2021)
      ! c4. Compute ZTHETA using ZLAMBDA0 (Eq. 26 in Gharamti, 2018)
      ZTHETA = SQRT((ZLAMBDA0-1/KENS)*ZHX_VAR+ZSIGMA_R(I)**2)
      ZLAM = ZLAMBDAP_MEAN
      ZSIG = ZLAMBDA_VAR(J,I)
      ZA = ZLAM**4/ZSIG**(3./2.)*SQRT(ZSIG**2+47*ZSIG*ZLAM**2+3*ZLAM**4)
      ZB = 1/ZSIG*(ZLAM**9+6*SQRT(3.)*ZSIG**3*ZA+75*ZSIG**2*ZLAM**5+ZSIG**3*ZLAM**3+21*ZSIG*ZLAM**7)**(1./3.)
      ZBETA = ZB/3+(ZLAM**3+7*ZSIG*ZLAM)/(3*ZSIG)+ZLAM**2*(ZSIG**2+14*ZSIG*ZLAM**2+ZLAM**4)/(3*ZSIG**2*ZB)
      ZALPHA = ZBETA/ZLAM-1
      ! c5. Compute updated value for the mean of ZLAMBDA corresponding to this state
      ZGAMMA_RATIO = 1/SQRT(2.)
      DO K = 2,KENS-1,2
        ZGAMMA_RATIO = ZGAMMA_RATIO*K/(K-1)
      ENDDO
      ZLBAR = ZGAMMA_RATIO/SQRT(3.1415*KENS)/SQRT(ABS((KENS-2.)/KENS*ZTHETA**2))/SQRT((1.+(ZD(I)/ZTHETA)**2/(KENS-2.))**(KENS+1))
      ZDTHETA_DLAMBDA = 0.5*ZHX_VAR*ZGAMMA*(1.-ZGAMMA+ZGAMMA*SQRT(ZLAMBDAP_MEAN))/(ZTHETA*SQRT(ZLAMBDAP_MEAN))
      ZLPRIME = ZLBAR*(KENS*ZD(I)**2-(KENS-2.)*ZTHETA**2)/((KENS-2.)*ZTHETA**2+ZD(I)**2)/ZTHETA*ZDTHETA_DLAMBDA
      ZA = 1-ZLAMBDAP_MEAN/ZBETA
      ZB = ZLBAR/ZLPRIME-2*ZLAMBDAP_MEAN
      ZC = ZLAMBDAP_MEAN**2-ZLBAR/ZLPRIME*ZLAMBDAP_MEAN
      ZDISCR = ZB**2-4*ZA*ZC
      ZLAMBDA1 = 0.5*(-ZB-SQRT(ZDISCR))/ZA
      ZLAMBDA2 = 0.5*(-ZB+SQRT(ZDISCR))/ZA
      IF (ABS(ZLAMBDA1-ZLAMBDAP_MEAN)>ABS(ZLAMBDA2-ZLAMBDAP_MEAN)) ZLAMBDA1 = ZLAMBDA2
      ZLAMBDA(J,I) = ZLAMBDA1
    ENDIF
  ENDDO
ENDDO
!
ENDIF
!
! 4. Inflate the prior ensemble for each state by the mean of the corresponding inflation distribution
WHERE(ZLAMBDA(:,:)<0.5) ZLAMBDA(:,:) = 0.5
WHERE(ZLAMBDA_VAR(:,:)<0.01) ZLAMBDA_VAR(:,:) = 0.01
DO I = 1,INB_PNT
  ZE_RED(:,I) = SQRT(MAXVAL(ZLAMBDA(I,:)))*ZE_RED(:,I)
  TPA%XINFL(IID_PNT(I)) = SQRT(MAXVAL(ZLAMBDA(I,:)))
  TPA%XINFL_VAR(IID_PNT(I)) = MAXVAL(ZLAMBDA_VAR(I,:))
ENDDO
!
DEALLOCATE(ZLAMBDA)
DEALLOCATE(ZLAMBDA_VAR)
DEALLOCATE(ZE_VAR)
!
IF (LHOOK) CALL DR_HOOK('ASSIM_ETKF_LOCAL:INFLATE_STATE',1,ZHOOK_HANDLE)
!
ENDSUBROUTINE INFLATE_STATE
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE ASSIM_ETKF_LOCAL
