SUBROUTINE ASSIM_OBS_CONF(KLISTING,KYEAR,KMONTH,KDAY,PTIME,KLON,KLAT)
!####################################################################
!
!!****  *ASSIM_OBS_CONF* - check the dimensions and date in the OBS file
!!
!!    PURPOSE
!!    -------
!!
!!    AUTHOR
!!    ------
!!      S. Munier   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!

USE MODE_TRIP_NETCDF
USE MODE_TRIP_DATE_NETCDF
USE MODD_TRIP_ASSIM

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB


IMPLICIT NONE

! Declaration of variables
INTEGER, INTENT(IN)  :: KLISTING
INTEGER, INTENT(IN)  :: KYEAR
INTEGER, INTENT(IN)  :: KMONTH
INTEGER, INTENT(IN)  :: KDAY
REAL,    INTENT(IN)  :: PTIME
INTEGER, INTENT(IN)  :: KLON
INTEGER, INTENT(IN)  :: KLAT

! Local parameter
CHARACTER(LEN=NF90_MAX_NAME) :: YFILE
CHARACTER(LEN=NF90_MAX_NAME) :: YVAR
CHARACTER(LEN=NF90_MAX_NAME) :: YUNITS
INTEGER, DIMENSION(3) :: IDIMLEN
INTEGER :: IFILE_ID
INTEGER :: IVAR_ID
INTEGER :: IRET
INTEGER :: IYEAR
INTEGER :: IMONTH
INTEGER :: IDAY
REAL    :: ZTIME
REAL    :: ZWORK(1)
INTEGER :: ILON
INTEGER :: ILAT
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ASSIM_OBS_CONF',0,ZHOOK_HANDLE)
!
YFILE = COBS_FILE(1:LEN_TRIM(COBS_FILE))
!
! * dimensions
!
YVAR = COBS_NAME
IDIMLEN = 0
CALL READ_DIMLEN(KLISTING,YFILE,YVAR,3,IDIMLEN)
!
ILON = IDIMLEN(1)
ILAT = IDIMLEN(2)
NOBS = IDIMLEN(3)
!
IF(ILON/=KLON.OR.ILAT/=KLAT)THEN
  WRITE(KLISTING,*)'For the variable : ',YVAR
  WRITE(KLISTING,*)'ASSIM_OBS_CONF: number of points in the observation variables (',ILON*ILAT,')'
  WRITE(KLISTING,*)'does not equal the number of points in the TRIP domain'
  WRITE(KLISTING,*)'NLON = ',KLON,' and NLAT = ',KLAT,' while OBS_LON = ',ILON,' and OBS_LAT = ',ILAT
  CALL ABORT_TRIP('ASSIM_OBS_CONF: number of points in the observation variables is /= than TRIP domain')
ENDIF
!
! * time
!
IRET=NF90_OPEN(YFILE,NF90_NOWRITE,IFILE_ID)
IF(IRET/=NF90_NOERR)THEN
  WRITE(KLISTING,*)'ASSIM_OBS_CONF : error in NF90_OPEN'
  CALL ABORT_TRIP('ASSIM_OBS_CONF : error in NF90_OPEN')
ENDIF
!
YVAR = 'time'
IRET=NF90_INQ_VARID(IFILE_ID,YVAR,IVAR_ID)
IF(IRET/=NF90_NOERR)THEN
  WRITE(KLISTING,*)'ASSIM_OBS_CONF : error in NF90_INQ_VARID'
  CALL ABORT_TRIP('ASSIM_OBS_CONF : error in NF90_INQ_VARID')
ENDIF
!
IRET=NF90_GET_ATT(IFILE_ID,IVAR_ID,'units',YUNITS)
IF(IRET/=NF90_NOERR)THEN
  WRITE(KLISTING,*)'ASSIM_OBS_CONF : error in NF90_GET_ATT'
  CALL ABORT_TRIP('ASSIM_OBS_CONF : error in NF90_GET_ATT')
ENDIF
!
ZWORK = 0
CALL READ_DATE(ZWORK,YUNITS,IYEAR,IMONTH,IDAY,ZTIME)
!
IF ( (KYEAR /= IYEAR) .OR. (KMONTH /= IMONTH) .OR. (KDAY /= IDAY) .OR. (PTIME /= ZTIME)) THEN
  WRITE(KLISTING,*)' DATE INCONSISTENCY: RESTART     FILE = ',KYEAR,KMONTH,KDAY,PTIME
  WRITE(KLISTING,*)' DATE INCONSISTENCY: OBSERVATION FILE = ',IYEAR,IMONTH,IDAY,ZTIME
  CALL ABORT_TRIP('ASSIM_OBS_CONF: DATE INCONSISTENCY')
ENDIF
!
IF (LHOOK) CALL DR_HOOK('ASSIM_OBS_CONF',1,ZHOOK_HANDLE)
!
END SUBROUTINE ASSIM_OBS_CONF
