SUBROUTINE ASSIM_LOCALIZATION(KOBS, KPNT, KNEXTST, KPREVST, KDTOBS, KOBS_STATE, PLOCAL)
!####################################################################
!
!!****  *ASSIM_LOCALIZATION*
!!
!!    PURPOSE
!!    -------
!!      Apply the localization from C. Emery
!!
!!    AUTHOR
!!    ------
!!      S. Munier   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_TRIP_ANALYSIS, ONLY : TPLOC
!
USE MODN_TRIP_ASSIM, ONLY : CLOCAL, NLOCAL_LEN, XLOCAL_AMP, NSMOOTH_LEN
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
INTEGER ,                      INTENT(IN)  :: KOBS
INTEGER ,                      INTENT(IN)  :: KPNT
INTEGER, DIMENSION(KPNT),      INTENT(IN)  :: KNEXTST
INTEGER, DIMENSION(8,KPNT),    INTENT(IN)  :: KPREVST
INTEGER, DIMENSION(KPNT),      INTENT(IN)  :: KDTOBS
INTEGER, DIMENSION(KOBS),      INTENT(IN)  :: KOBS_STATE
REAL,    DIMENSION(KPNT,KOBS), INTENT(OUT) :: PLOCAL
!
INTEGER :: ILOCAL_LEN
INTEGER :: JOBS, JSTATE, IDIST, JUP
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION',0,ZHOOK_HANDLE)
!
PLOCAL(:,:) = 0
ILOCAL_LEN = NLOCAL_LEN
!
DO JOBS = 1,KOBS
!
  ! 1. PLOCAL = 1 at observed cell
  JSTATE = KOBS_STATE(JOBS)
  PLOCAL(JSTATE,JOBS) = SMOOTHER_LENGTH(KDTOBS(JSTATE))
!
  ! 2. Compute PLOCAL downstream
  IF (CLOCAL=='COV') ILOCAL_LEN = TPLOC(JSTATE)%NLEN
  IDIST = 1
  DO WHILE (KNEXTST(JSTATE)>0 .AND. IDIST<ILOCAL_LEN)
    JSTATE = KNEXTST(JSTATE)
    PLOCAL(JSTATE,JOBS) = LOCALIZATION_FUN(IDIST,ILOCAL_LEN)
    PLOCAL(JSTATE,JOBS) = PLOCAL(JSTATE,JOBS) * SMOOTHER_LENGTH(KDTOBS(KOBS_STATE(JOBS)))
    IDIST = IDIST+1
  ENDDO
!
  ! 3. Compute PLOCAL upstream
  IF (CLOCAL=='COV' .OR. NLOCAL_LEN>0) THEN
    IDIST = 1
    JSTATE = KOBS_STATE(JOBS)
    IF(CLOCAL=='FUN') THEN
      CALL LOCALIZATION_UPSTREAM_FUN(IDIST,JSTATE,JOBS,KPREVST,ILOCAL_LEN,PLOCAL)
    ELSE
      !CALL LOCALIZATION_UPSTREAM_COV(IDIST,JSTATE,JOBS,KPREVST,J,PLOCAL)
      DO JUP = 1,8
        IF(KPREVST(JUP,JSTATE)<=0) EXIT
        IF(IDIST<TPLOC(KPREVST(JUP,JSTATE))%NLEN)THEN
          CALL LOCALIZATION_UPSTREAM_COV(IDIST,KPREVST(JUP,JSTATE),JOBS,KPREVST,ILOCAL_LEN,PLOCAL)
        ENDIF
      ENDDO
    ENDIF
  ENDIF
!
ENDDO
!
IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION',1,ZHOOK_HANDLE)
!
CONTAINS
!
FUNCTION LOCALIZATION_FUN(KDIST, KLOCAL_LEN)
  INTEGER, INTENT(IN) :: KDIST, KLOCAL_LEN
  REAL :: LOCALIZATION_FUN
  REAL(KIND=JPRB) :: ZHOOK_HANDLE
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:LOCALIZATION_FUN',0,ZHOOK_HANDLE)
  !
  IF (CLOCAL=='FUN') THEN
  !
    !LOCALIZATION_FUN = 1
    !LOCALIZATION_FUN = 1.-FLOAT(KDIST)/(KLOCAL_LEN+1.)
    LOCALIZATION_FUN = EXP(-FLOAT(KDIST)*3./(KLOCAL_LEN+1.))
  !
  ELSEIF (CLOCAL=='COV') THEN
  !
    !LOCALIZATION_FUN = MAX(1.-XLOCAL_AMP*TPLOC(JSTATE)%XCOV(KDIST),1e-5)
    LOCALIZATION_FUN = EXP(-20./(3.*XLOCAL_AMP)*(FLOAT(KDIST)/KLOCAL_LEN)**2) ! from Miyoshi (2007)
  !
  ENDIF
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:LOCALIZATION_FUN',1,ZHOOK_HANDLE)
  !
ENDFUNCTION LOCALIZATION_FUN
!
FUNCTION SMOOTHER_LENGTH(KDT)
  INTEGER, INTENT(IN) :: KDT
  REAL :: SMOOTHER_LENGTH
  REAL(KIND=JPRB) :: ZHOOK_HANDLE
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:SMOOTHER_LENGTH',0,ZHOOK_HANDLE)
  !
  IF (NSMOOTH_LEN>0) THEN
    SMOOTHER_LENGTH = EXP(-2.*KDT/NSMOOTH_LEN)
  ELSE
    SMOOTHER_LENGTH = 1
  ENDIF
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:SMOOTHER_LENGTH',1,ZHOOK_HANDLE)
  !
ENDFUNCTION SMOOTHER_LENGTH
!
RECURSIVE SUBROUTINE LOCALIZATION_UPSTREAM_FUN(KDIST, KSTATE, KOBS, KPREVST, KLOCAL_LEN, PLOCAL)
  INTEGER, INTENT(IN) :: KDIST, KSTATE, KOBS, KLOCAL_LEN
  INTEGER, DIMENSION(:,:), INTENT(IN) :: KPREVST
  REAL, DIMENSION(:,:), INTENT(INOUT) :: PLOCAL
  INTEGER :: JUP, JSTATE
  REAL(KIND=JPRB) :: ZHOOK_HANDLE
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:LOCALIZATION_UPSTREAM_FUN',0,ZHOOK_HANDLE)
  !
  IF (KDIST<=KLOCAL_LEN) THEN
    DO JUP = 1,8
      IF(KPREVST(JUP,KSTATE)<=0) EXIT
      JSTATE = KPREVST(JUP,KSTATE)
      PLOCAL(JSTATE,KOBS) = LOCALIZATION_FUN(KDIST,KLOCAL_LEN)
      PLOCAL(JSTATE,KOBS) = PLOCAL(JSTATE,KOBS) * SMOOTHER_LENGTH(KDTOBS(KOBS_STATE(KOBS)))
      CALL LOCALIZATION_UPSTREAM_FUN(KDIST+1,JSTATE,KOBS,KPREVST,KLOCAL_LEN,PLOCAL)
    ENDDO
  ENDIF
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:LOCALIZATION_UPSTREAM_FUN',1,ZHOOK_HANDLE)
  !
ENDSUBROUTINE LOCALIZATION_UPSTREAM_FUN
!
RECURSIVE SUBROUTINE LOCALIZATION_UPSTREAM_COV(KDIST, KSTATE, KOBS, KPREVST, KLOCAL_LEN, PLOCAL)
  INTEGER, INTENT(IN) :: KDIST, KSTATE, KOBS
  INTEGER, DIMENSION(:,:), INTENT(IN) :: KPREVST
  INTEGER, INTENT(OUT) :: KLOCAL_LEN
  REAL, DIMENSION(:,:), INTENT(INOUT) :: PLOCAL
  INTEGER :: JUP, JSTATE, ILOCAL_LEN_TMP
  REAL(KIND=JPRB) :: ZHOOK_HANDLE
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:LOCALIZATION_UPSTREAM_COV',0,ZHOOK_HANDLE)
  !
  KLOCAL_LEN = KDIST
  DO JUP = 1,8
    IF(KPREVST(JUP,KSTATE)<=0) EXIT
    JSTATE = KPREVST(JUP,KSTATE)
    IF(KDIST<TPLOC(JSTATE)%NLEN)THEN
      CALL LOCALIZATION_UPSTREAM_COV(KDIST+1,JSTATE,KOBS,KPREVST,ILOCAL_LEN_TMP,PLOCAL)
      IF(ILOCAL_LEN_TMP>KLOCAL_LEN) KLOCAL_LEN = ILOCAL_LEN_TMP
    ENDIF
  ENDDO
  PLOCAL(KSTATE,KOBS) = LOCALIZATION_FUN(KDIST,KLOCAL_LEN)
  PLOCAL(KSTATE,KOBS) = PLOCAL(KSTATE,KOBS) * SMOOTHER_LENGTH(KDTOBS(KOBS_STATE(KOBS)))
  !
  IF (LHOOK) CALL DR_HOOK('ASSIM_LOCALIZATION:LOCALIZATION_UPSTREAM_COV',1,ZHOOK_HANDLE)
  !
ENDSUBROUTINE LOCALIZATION_UPSTREAM_COV
!
END SUBROUTINE ASSIM_LOCALIZATION
