SUBROUTINE ASSIM_OBS(TPST, KLISTING, KSTATE, KLON, KLAT, KNB, KNOBS, KDTOBS, POBS, POBS_ERR)
!####################################################################
!
!!****  *ASSIM_OBS* - read observations
!!
!!    PURPOSE
!!    -------
!!
!!    AUTHOR
!!    ------
!!      S. Munier   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
USE MODD_TRIP_PAR, ONLY : LNCPRINT, XUNDEF
USE MODN_TRIP_RUN, ONLY : XTSTEP_RUN
!
USE MODE_TRIP_NETCDF
USE MODD_TRIP_ASSIM
USE MODN_TRIP_ASSIM
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
! Declaration of variables
TYPE(TRIP_STATE_t),    INTENT(INOUT) :: TPST
!
INTEGER,                        INTENT(IN)  :: KLISTING
INTEGER,                        INTENT(IN)  :: KSTATE
INTEGER,                        INTENT(IN)  :: KLON
INTEGER,                        INTENT(IN)  :: KLAT
INTEGER,                        INTENT(IN)  :: KNB
INTEGER, DIMENSION(KNB),        INTENT(OUT) :: KNOBS
INTEGER, DIMENSION(KSTATE,KNB), INTENT(OUT) :: KDTOBS
REAL,    DIMENSION(KSTATE,KNB), INTENT(OUT) :: POBS
REAL,    DIMENSION(KSTATE,KNB), INTENT(OUT) :: POBS_ERR
!
! Local parameter
REAL, DIMENSION(KLON,KLAT,NOBS) :: ZWORK, ZWORK_ERR
CHARACTER(LEN=NF90_MAX_NAME) :: YFILE
CHARACTER(LEN=NF90_MAX_NAME) :: YVAR
CHARACTER(LEN=NF90_MAX_NAME) :: YUNITS
INTEGER :: IFILE_ID
INTEGER :: IVAR_ID
INTEGER :: IRET
INTEGER :: I, J, K, JOBS, JSTATE, ITSTEP
REAL, DIMENSION(NOBS) :: ZWORK1D, ZTIME_OBS
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ASSIM_OBS',0,ZHOOK_HANDLE)
!
YFILE = COBS_FILE(1:LEN_TRIM(COBS_FILE))
!
IRET = NF90_OPEN(YFILE,NF90_NOWRITE,IFILE_ID)
!
! * Read time
!
YVAR = 'time'
!
IRET = NF90_INQ_VARID(IFILE_ID,YVAR,IVAR_ID)
IRET = NF90_GET_ATT(IFILE_ID,IVAR_ID,'units',YUNITS)
IRET = NF90_GET_VAR(IFILE_ID,IVAR_ID,ZWORK1D)
!
IF (YUNITS(1:4)=='seco') THEN
  ZTIME_OBS(:) = ZWORK1D(:)
ELSEIF (YUNITS(1:4)=='hour') THEN
  ZTIME_OBS(:) = 3600.*ZWORK1D(:)
ELSEIF (YUNITS(1:4)=='days') THEN
  ZTIME_OBS(:) = 86400.*ZWORK1D(:)
ENDIF
ITSTEP = INT(XTSTEP_OBS/XTSTEP_RUN)
IF(ITSTEP==0)THEN
  WRITE(KLISTING,*)'ASSIM_OBS : observation time step should be greater than forcing time step'
  CALL ABORT_TRIP('ASSIM_OBS : observation time step should be greater than forcing time step')
ENDIF
!
! * Read observations
!
YVAR = COBS_NAME(1:LEN_TRIM(COBS_NAME))
CALL NCREAD(KLISTING,IFILE_ID,YVAR,ZWORK,LNCPRINT)
!
IF (LUSE_OBS_ERR) THEN
  YVAR = COBS_ERR_NAME(1:LEN_TRIM(COBS_ERR_NAME))
  CALL NCREAD(KLISTING,IFILE_ID,YVAR,ZWORK_ERR,LNCPRINT)
ENDIF
!
! * Map obs grid on state vector
! * Compute number of observations at each time step
!
KNOBS(:) = 0
KDTOBS(:,:) = -1
POBS(:,:) = XUNDEF
POBS_ERR(:,:) = XSIGMA_R
JOBS = 1
!IF (ZTIME_OBS(JOBS)==0) JOBS = 2
DO K = ITSTEP,KNB,ITSTEP
  DO J = 1,KLAT
    DO I = 1,KLON
      JSTATE = TPST%NSTATE_IND(I,J)
      IF (JSTATE==-1) CYCLE
      IF (JOBS<=NOBS .AND. K*XTSTEP_RUN>=ZTIME_OBS(JOBS) .AND. ZWORK(I,J,JOBS)/=XUNDEF) THEN
        KNOBS(K) = KNOBS(K)+1
        KDTOBS(JSTATE,K) = 0
        POBS(JSTATE,K) = ZWORK(I,J,JOBS)
        IF (LUSE_OBS_ERR) POBS_ERR(JSTATE,K) = ZWORK_ERR(I,J,JOBS)
      ELSEIF (K>ITSTEP .AND. KDTOBS(JSTATE,K-ITSTEP)>=0 .AND. &
                             KDTOBS(JSTATE,K-ITSTEP)<NSMOOTH_LEN-1) THEN
        KNOBS(K) = KNOBS(K)+1
        KDTOBS(JSTATE,K) = KDTOBS(JSTATE,K-ITSTEP)+1
        POBS(JSTATE,K) = POBS(JSTATE,K-ITSTEP)
        IF (LUSE_OBS_ERR) POBS_ERR(JSTATE,K) = POBS_ERR(JSTATE,K-ITSTEP)
      ENDIF
    ENDDO
  ENDDO
  IF (JOBS<=NOBS .AND. K*XTSTEP_RUN>=ZTIME_OBS(JOBS)) JOBS = JOBS+1
ENDDO
!
IRET = NF90_CLOSE(IFILE_ID)
!
IF (LHOOK) CALL DR_HOOK('ASSIM_OBS',1,ZHOOK_HANDLE)
!
END SUBROUTINE ASSIM_OBS
