SUBROUTINE ASSIM_ENKF_LOCAL(TPST, TPA, KENS, KPNT, KOBS, PXB, POBS, POBS_ERR, KDTOBS, PHX, PXA)
!####################################################################
!
!!****  *ASSIM_ENKF_LOCAL*
!!
!!    PURPOSE
!!    -------
!!      Ensemble Kalman computation with localization
!!
!!    AUTHOR
!!    ------
!!      S. Munier   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!
!-------------------------------------------------------------------------------
!
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
USE MODD_TRIP_ANALYSIS, ONLY : TRIP_ANALYSIS_t
!
USE MODD_TRIP_PAR, ONLY : XUNDEF
USE MODD_TRIP_ASSIM
!
USE MODN_TRIP_ASSIM
USE MODI_ASSIM_BUILD_YO_HX
USE MODI_ASSIM_LOCALIZATION
USE MODI_ASSIM_INFLATE_FIELD
USE MODI_ASSIM_INVERSE
USE MODI_TEST_DIAG_WRITE
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
INCLUDE 'mpif.h'
!
!* 0.1    declarations of arguments
!
TYPE(TRIP_STATE_t),    INTENT(INOUT) :: TPST
TYPE(TRIP_ANALYSIS_t), INTENT(INOUT) :: TPA
!
INTEGER,                 INTENT(IN)    :: KENS
INTEGER,                 INTENT(IN)    :: KPNT
INTEGER,                 INTENT(IN)    :: KOBS
REAL,    DIMENSION(:,:), INTENT(IN)    :: PXB
REAL,    DIMENSION(:),   INTENT(IN)    :: POBS
REAL,    DIMENSION(:),   INTENT(IN)    :: POBS_ERR
INTEGER, DIMENSION(:),   INTENT(IN)    :: KDTOBS
REAL,    DIMENSION(:,:), INTENT(INOUT) :: PHX
REAL,    DIMENSION(:,:), INTENT(OUT)   :: PXA
!
!* 0.2    declarations of local variables
!
REAL, DIMENSION(KOBS,KENS) :: ZHX
REAL, DIMENSION(KOBS,KENS) :: ZD
REAL, DIMENSION(KPNT)      :: ZXB_MEAN
REAL, DIMENSION(KOBS)      :: ZHX_MEAN
REAL, DIMENSION(KOBS)      :: ZSIGMA_R
!
INTEGER, DIMENSION(:),ALLOCATABLE :: IOBS_INDEX
REAL, DIMENSION(:),   ALLOCATABLE :: ZYO
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLOCAL
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLOCAL_RED
REAL, DIMENSION(:,:), ALLOCATABLE :: ZLOCAL_PROC
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE_RED
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE_PROC
REAL, DIMENSION(:,:), ALLOCATABLE :: ZXA_PROC
REAL, DIMENSION(:,:), ALLOCATABLE :: ZC_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZPA_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWA_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWA_L_MEAN
REAL, DIMENSION(:,:), ALLOCATABLE :: ZD_L
REAL, DIMENSION(:),   ALLOCATABLE :: ZR_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZE_L
REAL, DIMENSION(:,:), ALLOCATABLE :: ZN_L
REAL, DIMENSION(:),   ALLOCATABLE :: ZS
REAL, DIMENSION(:,:), ALLOCATABLE :: ZU
!
REAL, DIMENSION(:),   ALLOCATABLE :: ZMASK
REAL, DIMENSION(:),   ALLOCATABLE :: ZDUM
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWORK
!
INTEGER :: ISEED, IERR, IDUM
INTEGER :: I, J, K, IOBS, IOBS_L, JSTATE
INTEGER :: IPNT_PROC, ISTART, ISTOP
LOGICAL :: GWRITE
!
INTEGER :: INB_PNT
INTEGER, DIMENSION(:), ALLOCATABLE :: IID_PNT
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('ASSIM_ENKF_LOCAL',0,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
!
  ALLOCATE(IOBS_INDEX(KOBS))
  ALLOCATE(ZE(KPNT,KENS))
  ALLOCATE(ZYO(KOBS))
  ALLOCATE(ZLOCAL(KPNT,KOBS))
!
! Build observation vector and model equivalent of obs
!
  CALL ASSIM_BUILD_YO_HX(TPST, KENS, KOBS, KPNT, IOBS_INDEX, POBS, PXB, ZYO, ZHX)
!
  DO I = 1, KOBS
    IF (KDTOBS(IOBS_INDEX(I))==0) THEN
      PHX(IOBS_INDEX(I),:) = ZHX(I,:)
    ELSE
      ZHX(I,:) = PHX(IOBS_INDEX(I),:)
    ENDIF
  ENDDO
!
! Localization
!
  CALL ASSIM_LOCALIZATION(KOBS, KPNT, TPST%NNEXTST, TPST%NPREVST, KDTOBS, IOBS_INDEX, ZLOCAL)
!
! Innovation
!
  DO I = 1,KENS
    ZD(:,I) = ZYO(:) - ZHX(:,I)
  ENDDO
!
! Domain reduction
!
  INB_PNT = 0
  ALLOCATE(IID_PNT(KPNT))
  DO I = 1,KPNT
    IF (SUM(ZLOCAL(I,:))>0) THEN
      INB_PNT = INB_PNT+1
      IID_PNT(INB_PNT) = I
    ENDIF
  ENDDO
  IPNT_PROC = CEILING(INB_PNT*1./NPROC_ASSIM)
  ALLOCATE(ZLOCAL_RED(KOBS,IPNT_PROC*NPROC_ASSIM))
  ZLOCAL_RED(:,:) = 0.
  DO I = 1,INB_PNT
    ZLOCAL_RED(:,I) = ZLOCAL(IID_PNT(I),:)
  ENDDO
!
! Build mean background state and mean model equivalent of obs
!
  ZXB_MEAN(:) = 0.
  ZHX_MEAN(:) = 0.
  DO I = 1, KENS
    ZXB_MEAN(:) = ZXB_MEAN(:) + PXB(:,I)
    ZHX_MEAN(:) = ZHX_MEAN(:) + ZHX(:,I)
  ENDDO
  ZXB_MEAN(:) = ZXB_MEAN(:)/REAL(KENS)
  ZHX_MEAN(:) = ZHX_MEAN(:)/REAL(KENS)
  DO I = 1, KENS
    ZE(:,I) = PXB(:,I)-ZXB_MEAN(:)
    ZHX(:,I) = ZHX(:,I)-ZHX_MEAN(:)
  ENDDO
!
! Build background error
!
  ALLOCATE(ZE_RED(KENS,IPNT_PROC*NPROC_ASSIM))
  DO I = 1, INB_PNT
    ZE_RED(:,I) = ZE(IID_PNT(I),:)
  ENDDO
!
  DO I = 1, KOBS
    IF (LUSE_OBS_ERR) THEN
      ZSIGMA_R(I) = MAX(POBS_ERR(IOBS_INDEX(I)),1E-6)
    ELSE
      IF (MOD(IOBS_INDEX(I),2)==1) THEN
        ZSIGMA_R(I) = MAX(XSIGMA_R_Q*ZYO(I),0.1)
      ELSE
        ZSIGMA_R(I) = XSIGMA_R_H
      ENDIF
    ENDIF
  ENDDO
!
! Write localization matrix in diag
!
  CALL TEST_DIAG_WRITE('LOCAL',GWRITE)
  IF (GWRITE) THEN
    TPA%XLOCAL(:,:) = XUNDEF
    DO I = 1,KOBS
      JSTATE = (IOBS_INDEX(I)-1)/2+1
      TPA%XLOCAL(:,JSTATE) = ZLOCAL(:,I)
    ENDDO
  ENDIF
!
  DEALLOCATE(ZE)
  DEALLOCATE(ZYO)
  DEALLOCATE(ZLOCAL)
!
ENDIF
!
! Serialization
!
CALL MPI_BCAST(INB_PNT, 1, MPI_INTEGER, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(IPNT_PROC, 1, MPI_INTEGER, NPIO_ASSIM, NCOMM_ASSIM, IERR)
!
ALLOCATE(ZE_PROC(KENS,IPNT_PROC))
ALLOCATE(ZLOCAL_PROC(KOBS,IPNT_PROC))
!
CALL MPI_BCAST(ZHX_MEAN, KOBS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(ZHX, KOBS*KENS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(ZD, KOBS*KENS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_BCAST(ZSIGMA_R, KOBS, MPI_DOUBLE, NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_SCATTER(ZE_RED, KENS*IPNT_PROC, MPI_DOUBLE, ZE_PROC, KENS*IPNT_PROC, MPI_DOUBLE, &
                 NPIO_ASSIM, NCOMM_ASSIM, IERR)
CALL MPI_SCATTER(ZLOCAL_RED, KOBS*IPNT_PROC, MPI_DOUBLE, ZLOCAL_PROC, KOBS*IPNT_PROC, MPI_DOUBLE, &
                 NPIO_ASSIM, NCOMM_ASSIM, IERR)
!
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
  DEALLOCATE(ZE_RED)
  DEALLOCATE(ZLOCAL_RED)
ENDIF
!
ISTART = NRANK_ASSIM*IPNT_PROC+1
ISTOP  = MIN((NRANK_ASSIM+1)*IPNT_PROC,INB_PNT)
!
ALLOCATE(ZXA_PROC(KENS,IPNT_PROC))
ZXA_PROC(:,:) = 0.
!
! LOCAL KALMAN
!
ALLOCATE(ZE_L(1,KENS))
!
DO I = 1,ISTOP-ISTART+1
  !
  IOBS_L = 0
  DO J = 1,KOBS
    IF (ZLOCAL_PROC(J,I)>0) IOBS_L = IOBS_L+1
  ENDDO
  IF (IOBS_L==0) CYCLE
  !
  ALLOCATE(ZPA_L(IOBS_L,IOBS_L))
  ALLOCATE(ZWA_L(IOBS_L,KENS))
  ALLOCATE(ZS(IOBS_L))
  ALLOCATE(ZU(IOBS_L,IOBS_L))
  ALLOCATE(ZR_L(IOBS_L))
  ALLOCATE(ZN_L(IOBS_L,KENS))
  ALLOCATE(ZD_L(IOBS_L,KENS))
  ALLOCATE(ZC_L(IOBS_L,IOBS_L))
  !
  IOBS = 0
  DO J = 1,KOBS
    IF (ZLOCAL_PROC(J,I)>0) THEN
      IOBS = IOBS+1
      ZR_L(IOBS) = ZSIGMA_R(J)*ZSIGMA_R(J)
      ZN_L(IOBS,:) = ZHX(J,:)
      ZD_L(IOBS,:) = ZD(J,:) * ZLOCAL_PROC(J,I)
    ENDIF
  ENDDO
  ZE_L(1,:) = ZE_PROC(:,I)
  !
  ! LOCAL KALMAN
  !
  ! XA = XB + PHt(inv(HPHt+R))*(Y-HXB)
  ! XA = XB + E*(HE)t*(inv(HE(HE)t+R))*(Y-HXB)
  !
  ! ZC = HE(HE)t = ZN*ZNt
  ZC_L = MATMUL(ZN_L,TRANSPOSE(ZN_L))
  !
  ! ZPA = inv(HE(HE)t+R)
  !
  ZU(:,:) = ZC_L(:,:)
  DO IOBS = 1,IOBS_L
    ZU(IOBS,IOBS) = ZU(IOBS,IOBS)+ZR_L(IOBS)
  ENDDO
  !
  !IDUM = 3*KENS-1
  IDUM = 10000
  ALLOCATE(ZDUM(IDUM))
  IDUM = -1
  CALL DSYEV('V','U',IOBS_L,ZU,IOBS_L,ZS,ZDUM,IDUM,IERR)
  IDUM = MIN(10000,INT(ZDUM(1)))
  CALL DSYEV('V','U',IOBS_L,ZU,IOBS_L,ZS,ZDUM,IDUM,IERR)
  DEALLOCATE(ZDUM)
  !
  ALLOCATE(ZWORK(IOBS_L,IOBS_L))
  ZWORK(:,:) = 0.
  DO K = 1,IOBS_L
    ZWORK(K,K) = 1./MAX(ZS(K),1E-6)
  ENDDO
  ZPA_L = MATMUL(ZU,MATMUL(ZWORK,TRANSPOSE(ZU)))
  DEALLOCATE(ZWORK)
  !
  ! ZWA = E*(HE)t*(inv(HE(HE)t+R))
  ZWA_L = MATMUL(ZE_L,MATMUL(TRANSPOSE(ZN_L),ZPA_L))
  !
  ! ZXA = E*(HE)t*(inv(HE(HE)t+R))*(Y-HXB)
  ALLOCATE(ZWORK(1,KENS))
  ZWORK = MATMUL(ZWA_L,ZD_L)
  ZXA_PROC(:,I) = ZWORK(1,:)
  DEALLOCATE(ZWORK)
  !
  DEALLOCATE(ZR_L)
  DEALLOCATE(ZN_L)
  DEALLOCATE(ZD_L)
  DEALLOCATE(ZC_L)
  DEALLOCATE(ZPA_L)
  DEALLOCATE(ZWA_L)
  DEALLOCATE(ZS)
  DEALLOCATE(ZU)
  !
ENDDO
!
DEALLOCATE(ZE_L)
!
! Gathering
!
IF (NRANK_ASSIM==NPIO_ASSIM) ALLOCATE(ZWORK(KENS,IPNT_PROC*NPROC_ASSIM))
CALL MPI_GATHER(ZXA_PROC,IPNT_PROC*KENS,MPI_DOUBLE,ZWORK,IPNT_PROC*KENS,MPI_DOUBLE, &
                NPIO_ASSIM,NCOMM_ASSIM,IERR)
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
  PXA(:,:) = PXB(:,:)
  DO I = 1,INB_PNT
    PXA(IID_PNT(I),:) = PXB(IID_PNT(I),:)+ZWORK(:,I)
  ENDDO
  DEALLOCATE(ZWORK)
  DEALLOCATE(IID_PNT)
ENDIF
!
DEALLOCATE(ZXA_PROC)
DEALLOCATE(ZLOCAL_PROC)
DEALLOCATE(ZE_PROC)
!
! Update
!
IF (NRANK_ASSIM==NPIO_ASSIM) THEN
!
  TPA%XB(:,:) = PXB(:,:)
  TPA%XA(:,:) = PXA(:,:)
  TPA%XINNOV(:) = XUNDEF
  DO I = 1,KOBS
    TPA%XINNOV(IOBS_INDEX(I)) = SUM(ZD(I,:))/REAL(KENS)
  ENDDO
!
  DEALLOCATE(IOBS_INDEX)
!
ENDIF
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('ASSIM_ENKF_LOCAL',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE ASSIM_ENKF_LOCAL
