!     ###################################################################
SUBROUTINE GWF_STATE (TP,TPG,TPST, &
                      KLON,KLAT,KSTATE,OPRINT,PTSTEP_RUN,PTSTEP, &
                      PDRAIN,PHS,PHG_OLD,PQGCELL,PWTD,PFWTD,     &
                      PHGHS,PGOUT,PGNEG,                         &
                      PGSTO_ALL,PGSTO2_ALL,PGIN_ALL,PGOUT_ALL    )
!     ###################################################################
!
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
!!
!!
!!
!!    AUTHOR
!!    ------
!!    S. Munier   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!-------------------------------------------------------------------------------
!
USE MODD_TRIP,       ONLY : TRIP_t
USE MODD_TRIP_GRID,  ONLY : TRIP_GRID_t
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
!
USE MODD_TRIP_MPI
USE MODE_TRIP_GRID_STATE
!
USE MODI_GWF
USE MODI_WAITING_MPI
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
#ifdef SFX_MPI
INCLUDE "mpif.h"
#endif
!
!*      0.1    declarations of arguments
!
!
TYPE(TRIP_t),            INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t),       INTENT(INOUT) :: TPG
TYPE(TRIP_STATE_t),      INTENT(INOUT) :: TPST
!
INTEGER,                 INTENT(IN) :: KLON
INTEGER,                 INTENT(IN) :: KLAT
INTEGER,                 INTENT(IN) :: KSTATE
LOGICAL,                 INTENT(IN) :: OPRINT
!
REAL,                    INTENT(IN) :: PTSTEP_RUN
REAL,                    INTENT(IN) :: PTSTEP
!
REAL, DIMENSION(:),      INTENT(IN) :: PDRAIN     ! Input drainage                [kg/s]
!
REAL, DIMENSION(:),      INTENT(IN) :: PHS        ! river height at t             [m]
!
REAL, DIMENSION(:), INTENT(INOUT)   :: PHG_OLD    ! water table elevation at t-1  [m]
!
REAL, DIMENSION(:), INTENT(OUT),   OPTIONAL :: PQGCELL
REAL, DIMENSION(:), INTENT(OUT),   OPTIONAL :: PWTD
REAL, DIMENSION(:), INTENT(OUT),   OPTIONAL :: PFWTD
REAL, DIMENSION(:), INTENT(OUT),   OPTIONAL :: PHGHS
REAL, DIMENSION(:), INTENT(OUT),   OPTIONAL :: PGOUT
REAL, DIMENSION(:), INTENT(OUT),   OPTIONAL :: PGNEG
!
REAL,               INTENT(OUT),   OPTIONAL :: PGSTO_ALL
REAL,               INTENT(OUT),   OPTIONAL :: PGSTO2_ALL
REAL,               INTENT(OUT),   OPTIONAL :: PGIN_ALL
REAL,               INTENT(OUT),   OPTIONAL :: PGOUT_ALL
!
!*      0.2    declarations of local variables
!
REAL, DIMENSION(:,:), ALLOCATABLE :: ZDRAIN, ZHS, ZHGROUND, ZHG_OLD, ZSURF_STO
REAL, DIMENSION(:,:), ALLOCATABLE :: ZQGCELL, ZWTD, ZFWTD, ZHGHS, ZGOUT, ZGNEG
REAL, DIMENSION(:)  , ALLOCATABLE :: ZSTATE
!
INTEGER :: IERR
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
! *     1.  INITIALIZATION
!           --------------
!
IF (LHOOK) CALL DR_HOOK('GWF_STATE',0,ZHOOK_HANDLE)
!
IF (NRANK==NPIO) THEN
  ALLOCATE(ZDRAIN(KLON,KLAT))
  ALLOCATE(ZHS(KLON,KLAT))
  ALLOCATE(ZHGROUND(KLON,KLAT))
  ALLOCATE(ZHG_OLD(KLON,KLAT))
  ALLOCATE(ZSURF_STO(KLON,KLAT))
  ALLOCATE(ZQGCELL(KLON,KLAT))
  ALLOCATE(ZWTD(KLON,KLAT))
  ALLOCATE(ZFWTD(KLON,KLAT))
  ALLOCATE(ZHGHS(KLON,KLAT))
  ALLOCATE(ZGOUT(KLON,KLAT))
  ALLOCATE(ZGNEG(KLON,KLAT))
  ALLOCATE(ZSTATE(KSTATE*NPROC))
ELSE
  ALLOCATE(ZSTATE(0))
ENDIF
!
CALL WAITING_MPI('GWF_STATE:BEFORE_GATHER')
!
!-------------------------------------------------------------------------------
!
! *     2.  GATHER FIELDS TO MAIN PROC
!           --------------------------
!
CALL MPI_GATHER(PDRAIN,KSTATE,MPI_DOUBLE,ZSTATE,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,ZDRAIN)
!
CALL MPI_GATHER(PHS,KSTATE,MPI_DOUBLE,ZSTATE,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,ZHS)
!
CALL MPI_GATHER(TPST%XHGROUND,KSTATE,MPI_DOUBLE,ZSTATE,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,ZHGROUND)
!
CALL MPI_GATHER(PHG_OLD,KSTATE,MPI_DOUBLE,ZSTATE,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,ZHG_OLD)
!
CALL MPI_GATHER(TPST%XSURF_STO,KSTATE,MPI_DOUBLE,ZSTATE,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,ZSURF_STO)
!
!-------------------------------------------------------------------------------
!
! *     3.  MAIN GROUDWATER ROUTINE
!           -----------------------
!
IF (NRANK==NPIO) THEN
  CALL GWF(TP, TPG, &
           KLON,KLAT,OPRINT,PTSTEP_RUN,PTSTEP,ZDRAIN,ZHS,ZHGROUND,ZHG_OLD, &
           PSURF_STO=ZSURF_STO,PQGCELL=ZQGCELL,PWTD=ZWTD,PFWTD=ZFWTD,      &
           PHGHS=ZHGHS,PGOUT=ZGOUT,PGNEG=ZGNEG,PGSTO_ALL=PGSTO_ALL,        &
           PGSTO2_ALL=PGSTO2_ALL,PGIN_ALL=PGIN_ALL,PGOUT_ALL=PGOUT_ALL     )
ENDIF
!
!-------------------------------------------------------------------------------
!
! *     4.  SCATTER FIELDS TO ALL PROCS
!           ---------------------------
!
CALL WAITING_MPI('GWF_STATE:BEFORE_SCATTER')
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZHGROUND,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,TPST%XHGROUND,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZHG_OLD,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PHG_OLD,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSURF_STO,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,TPST%XSURF_STO,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZQGCELL,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PQGCELL,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZWTD,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PWTD,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZFWTD,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PFWTD,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZHGHS,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PHGHS,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZGOUT,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PGOUT,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
IF (NRANK==NPIO) CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZGNEG,ZSTATE)
CALL MPI_SCATTER(ZSTATE,KSTATE,MPI_DOUBLE,PGNEG,KSTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
!
!-------------------------------------------------------------------------------
!
! *     5.  FINALIZE
!           ---------------------------
!
IF (NRANK==NPIO) THEN
  DEALLOCATE(ZDRAIN)
  DEALLOCATE(ZHS)
  DEALLOCATE(ZHGROUND)
  DEALLOCATE(ZHG_OLD)
  DEALLOCATE(ZSURF_STO)
  DEALLOCATE(ZQGCELL)
  DEALLOCATE(ZWTD)
  DEALLOCATE(ZFWTD)
  DEALLOCATE(ZHGHS)
  DEALLOCATE(ZGOUT)
  DEALLOCATE(ZGNEG)
ENDIF
DEALLOCATE(ZSTATE)
!
IF (LHOOK) CALL DR_HOOK('GWF_STATE',1,ZHOOK_HANDLE)
!
END SUBROUTINE GWF_STATE
