!     #########
      SUBROUTINE INIT_TRIP_ANALYSIS (TP, TPG, TPST, TPA, KLISTING, KPNT, KENS)
!     #######################################################################
!
!!****  *INIT_TRIP_ANALYSIS*
!!
!!    PURPOSE
!!    -------
!
!     Define the name and unit of each trip output variable.
!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      S. Munier
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    27/11/19
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
USE MODD_TRIP,       ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
USE MODD_TRIP_ANALYSIS, ONLY : TRIP_ANALYSIS_t
!
USE MODD_TRIP_PAR, ONLY : XUNDEF, LNCPRINT
USE MODD_TRIP_ASSIM
USE MODN_TRIP_ASSIM, ONLY : XINFL_VAR_INIT
!
USE MODE_TRIP_GRID_STATE, ONLY : TRIP_GRID_TO_STATE
USE MODE_TRIP_NETCDF
USE MODI_TEST_DIAG_WRITE
!
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE PARKIND1, ONLY : JPRB
!
USE NETCDF
!
IMPLICIT NONE
!
!
!*      0.1    declarations of arguments
!
TYPE(TRIP_t),       INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t),  INTENT(INOUT) :: TPG
TYPE(TRIP_STATE_t), INTENT(INOUT) :: TPST
TYPE(TRIP_ANALYSIS_t), INTENT(INOUT) :: TPA
INTEGER, INTENT(IN) :: KLISTING, KPNT, KENS
!
!*      0.2    declarations of local variables
!
CHARACTER(LEN=50) :: YANALYSIS = 'TRIP_ANALYSIS.nc'
CHARACTER(LEN=50) :: YTITLE    = 'TRIP analysis variables'
CHARACTER(LEN=50) :: YFILE, YTIMEUNIT, YWORK
INTEGER :: INCID, IVAR_ID, IC
INTEGER :: ISTADIM, IOBSDIM, IENSDIM, ITIMEDIM
INTEGER :: ITIME_ID, ILON_ID, ILAT_ID, VAR_ID
INTEGER :: ILON, ILAT, K
REAL,   DIMENSION(:), ALLOCATABLE :: ZLON, ZLAT
REAL*4, DIMENSION(:), ALLOCATABLE :: ZLON_ST, ZLAT_ST
REAL*4 :: ZMISSVAL
LOGICAL :: GWRITE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('INIT_TRIP_ANALYSIS',0,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
! * Allocate trip grid arguments
!-------------------------------------------------------------------------------
!
ALLOCATE(TPA%XB        (KPNT,KENS))
ALLOCATE(TPA%XA        (KPNT,KENS))
ALLOCATE(TPA%XINNOV    (KPNT))
CALL TEST_DIAG_WRITE('LOCAL',GWRITE)
IF (GWRITE) ALLOCATE(TPA%XLOCAL (KPNT,KPNT))
!CALL TEST_DIAG_WRITE('KALMAN',GWRITE)
!IF (GWRITE) ALLOCATE(TPA%XK     (KPNT,KPNT))
!
ALLOCATE(TPA%XINFL     (KPNT))
ALLOCATE(TPA%XINFL_VAR (KPNT))
CALL TRIP_GRID_TO_STATE(TPST%NSTATE_LON,TPST%NSTATE_LAT,TP%XINFL,TPA%XINFL)
TPA%XINFL_VAR(:) = XINFL_VAR_INIT
!
!-------------------------------------------------------------------------------
! * Create netcdf file
!-------------------------------------------------------------------------------
!
!Read time units from observation file
!
YFILE = COBS_FILE(1:LEN_TRIM(COBS_FILE))
IC = NF90_OPEN(YFILE,NF90_NOWRITE,INCID)
IC = NF90_INQ_VARID(INCID,'time',IVAR_ID)
IC = NF90_GET_ATT(INCID,IVAR_ID,'units',YTIMEUNIT)
IC = NF90_CLOSE(INCID)
!
!Create netcdf file
!
YWORK = YANALYSIS(1:LEN_TRIM(YANALYSIS))
IC = NF90_CREATE(YWORK,NF90_64BIT_OFFSET,INCID)
IF(IC/=NF90_NOERR)THEN
  WRITE(KLISTING,*)'NCCREATE_ANALYSIS for TRIP : Error create file ',YANALYSIS(1:LEN_TRIM(YANALYSIS))
  WRITE(KLISTING,*)NF90_STRERROR(IC)
  CALL ABORT_TRIP('NCCREATE_ANALYSIS for TRIP : Error create file')
ELSEIF(LNCPRINT)THEN
  WRITE(KLISTING,*)'NCCREATE_ANALYSIS for TRIP : Success in creating file ',YANALYSIS(1:LEN_TRIM(YANALYSIS))
ENDIF
!
ZMISSVAL = REAL(XUNDEF)
!
!Global attributes
!
YWORK = YTITLE(1:LEN_TRIM(YTITLE))
IC = NF90_PUT_ATT(INCID,NF90_GLOBAL,'title',YWORK)
YWORK = 'COARDS'
IC = NF90_PUT_ATT(INCID,NF90_GLOBAL,'Conventions',YWORK)
!
!Dimensions
!
IC = NF90_DEF_DIM(INCID,'state',KPNT,ISTADIM)
IC = NF90_DEF_DIM(INCID,'observation',KPNT,IOBSDIM)
IC = NF90_DEF_DIM(INCID,'ensemble',KENS,IENSDIM)
IC = NF90_DEF_DIM(INCID,'time',NF90_UNLIMITED,ITIMEDIM)
!
!Variables
!
YWORK = YTIMEUNIT(1:LEN_TRIM(YTIMEUNIT))
IC = NF90_DEF_VAR(INCID,'time',NF90_INT,ITIMEDIM,ITIME_ID)
IC = NF90_PUT_ATT(INCID,ITIME_ID,'units',YWORK)
!
YWORK = 'LON'
IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/IOBSDIM/),ILON_ID)
IC = NF90_PUT_ATT(INCID,ILON_ID,'long_name','Longitude of observations and states')
IC = NF90_PUT_ATT(INCID,ILON_ID,'units','degrees East')
!
YWORK = 'LAT'
IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/IOBSDIM/),ILAT_ID)
IC = NF90_PUT_ATT(INCID,ILAT_ID,'long_name','Latitude of observations and states')
IC = NF90_PUT_ATT(INCID,ILAT_ID,'units','degrees North')
!
YWORK = 'XB'
CALL TEST_DIAG_WRITE(YWORK,GWRITE)
IF(GWRITE)THEN
  IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/ISTADIM,IENSDIM,ITIMEDIM/),VAR_ID)
  IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Background state vector')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
ENDIF
!
YWORK = 'XA'
CALL TEST_DIAG_WRITE(YWORK,GWRITE)
IF(GWRITE)THEN
  IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/ISTADIM,IENSDIM,ITIMEDIM/),VAR_ID)
  IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Analyzed state vector')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
ENDIF
!
YWORK = 'INFL'
CALL TEST_DIAG_WRITE(YWORK,GWRITE)
IF(GWRITE)THEN
  IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/ISTADIM,ITIMEDIM/),VAR_ID)
  IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Inflation')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
ENDIF
!
YWORK = 'INFL_VAR'
CALL TEST_DIAG_WRITE(YWORK,GWRITE)
IF(GWRITE)THEN
  IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/ISTADIM,ITIMEDIM/),VAR_ID)
  IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Inflation variance')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
ENDIF
!
YWORK = 'INNOV'
CALL TEST_DIAG_WRITE(YWORK,GWRITE)
IF(GWRITE)THEN
  IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/IOBSDIM,ITIMEDIM/),VAR_ID)
  IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Innovation')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
  IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
ENDIF
!
YWORK = 'LOCAL'
CALL TEST_DIAG_WRITE(YWORK,GWRITE)
IF(GWRITE)THEN
 IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/ISTADIM,IOBSDIM,ITIMEDIM/),VAR_ID)
 IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Localization mask')
 IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
 IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
ENDIF
!
!YWORK = 'KALMAN'
!CALL TEST_DIAG_WRITE(YWORK,GWRITE)
!IF(GWRITE)THEN
! IC = NF90_DEF_VAR(INCID,YWORK,NF90_FLOAT,(/ISTADIM,IOBSDIM,ITIMEDIM/),VAR_ID)
! IC = NF90_PUT_ATT(INCID,VAR_ID,'long_name','Kalman gain')
! IC = NF90_PUT_ATT(INCID,VAR_ID,'units','-')
! IC = NF90_PUT_ATT(INCID,VAR_ID,'_FillValue',ZMISSVAL)
!ENDIF
!
IC = NF90_ENDDEF(INCID)
IF(IC/=NF90_NOERR)THEN
  WRITE(KLISTING,*)'NCCREATE_ANALYSIS for TRIP : Error file definition'
  WRITE(KLISTING,*)NF90_STRERROR(IC)
  CALL ABORT_TRIP('NCCREATE_ANALYSIS for TRIP :  Error file definition')
ELSEIF(LNCPRINT)THEN
    WRITE(KLISTING,*)'NCCREATE_ANALYSIS for TRIP : file definition is ok'
ENDIF
!
!Write coordinates
!
ILON = SIZE(TPG%XAREA,1)
ILAT = SIZE(TPG%XAREA,2)
ALLOCATE(ZLON(ILON))
ALLOCATE(ZLAT(ILAT))
ALLOCATE(ZLON_ST(KPNT))
ALLOCATE(ZLAT_ST(KPNT))
CALL GET_LONLAT_TRIP(TPG,ILON,ILAT,ZLON,ZLAT)
DO K = 1,KPNT
  ZLON_ST(K) = ZLON(TPST%NSTATE_LON(K))
  ZLAT_ST(K) = ZLAT(TPST%NSTATE_LAT(K))
ENDDO
IC = NF90_PUT_VAR(INCID,ILON_ID,ZLON_ST)
IC = NF90_PUT_VAR(INCID,ILAT_ID,ZLAT_ST)
DEALLOCATE(ZLON)
DEALLOCATE(ZLAT)
DEALLOCATE(ZLON_ST)
DEALLOCATE(ZLAT_ST)
!
IF(LNCPRINT)THEN
  WRITE(KLISTING,*)'NCCREATE_ANALYSIS ',YANALYSIS(1:LEN_TRIM(YANALYSIS)),' for TRIP OK !'
ENDIF
!
IC = NF90_CLOSE(INCID)
IF(LNCPRINT)WRITE(KLISTING,*)'NCCLOSE for TRIP : Close file ',YANALYSIS(1:LEN_TRIM(YANALYSIS))
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('INIT_TRIP_ANALYSIS',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
END SUBROUTINE INIT_TRIP_ANALYSIS
