MODULE MODD_SURFEX_TRIP_n
!
USE MODD_TRIP, ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_t
USE MODD_TRIP_LAKE, ONLY : TRIP_LAKE_t
!
!---------------------------------------------------------------------------
!
TYPE TRIP_MODEL_t
!
TYPE(TRIP_t)          :: TP
TYPE(TRIP_GRID_t)     :: TPG
TYPE(TRIP_STATE_t)    :: TPST
TYPE(TRIP_DIAG_t)     :: TPDG
TYPE(TRIP_LAKE_t)     :: TPLK
!
END TYPE TRIP_MODEL_t
!
END MODULE MODD_SURFEX_TRIP_n
