MODULE MODD_OFF_TRIP_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODD_SURFEX_TRIP_n, ONLY : TRIP_MODEL_t
!
TYPE(TRIP_MODEL_t), ALLOCATABLE, TARGET, SAVE :: YTRIP_LIST(:)
TYPE(TRIP_MODEL_t), POINTER :: YTRIP_CUR => NULL()
!$OMP THREADPRIVATE(YTRIP_CUR)
!
CONTAINS
!
SUBROUTINE GOTO_MODEL_TRIP(KMODEL)

INTEGER, INTENT(IN) :: KMODEL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_TRIP_n:GOTO_MODEL_TRIP",0,ZHOOK_HANDLE)
!
YTRIP_CUR => YTRIP_LIST(KMODEL)
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_TRIP_n:GOTO_MODEL_TRIP",1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_MODEL_TRIP
!
SUBROUTINE TRIP_ALLOC_LIST(KMODEL)
!
USE MODI_TRIP_ALLOC
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_TRIP_n:TRIP_ALLOC_LIST",0,ZHOOK_HANDLE)
!
ALLOCATE(YTRIP_LIST(KMODEL))
!
DO J = 1,KMODEL
  CALL TRIP_ALLOC(YTRIP_LIST(J))
ENDDO
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_TRIP_n:TRIP_ALLOC_LIST",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_ALLOC_LIST
!
SUBROUTINE TRIP_DEALLO_LIST
!
USE MODI_TRIP_DEALLO
!
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_TRIP_n:TRIP_DEALLO_LIST",0,ZHOOK_HANDLE)
!
DO J=1,SIZE(YTRIP_LIST)
  CALL TRIP_DEALLO(YTRIP_LIST(J))
ENDDO
!
IF (ASSOCIATED(YTRIP_CUR)) NULLIFY(YTRIP_CUR)
IF (ALLOCATED(YTRIP_LIST)) DEALLOCATE(YTRIP_LIST)
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_TRIP_n:TRIP_DEALLO_LIST",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DEALLO_LIST
!
END MODULE MODD_OFF_TRIP_n
