MODULE MODD_TRIP_ANALYSIS
!
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE PARKIND1, ONLY : JPRB
!
IMPLICIT NONE
!
TYPE TRIP_ANALYSIS_t
!
REAL, POINTER, DIMENSION(:,:) :: XB     ! background state
REAL, POINTER, DIMENSION(:,:) :: XA     ! analyzed state
REAL, POINTER, DIMENSION(:)   :: XINFL  ! inflation
REAL, POINTER, DIMENSION(:)   :: XINFL_VAR ! inflation variance
REAL, POINTER, DIMENSION(:)   :: XINNOV ! innovation
REAL, POINTER, DIMENSION(:,:) :: XLOCAL ! localization mask
REAL, POINTER, DIMENSION(:,:) :: XK     ! Kalman gain matrix
!
END TYPE TRIP_ANALYSIS_t
!
TYPE TRIP_LOCAL_t
!
INTEGER                        :: NLEN
!INTEGER, POINTER, DIMENSION(:) :: NDOWN_STATE
!REAL, POINTER, DIMENSION(:)    :: XCOV
!
END TYPE TRIP_LOCAL_t
!
REAL,               DIMENSION(:), ALLOCATABLE :: XHMEAN ! mean river depth
TYPE(TRIP_LOCAL_t), DIMENSION(:), ALLOCATABLE :: TPLOC
!
CONTAINS
!
SUBROUTINE TRIP_ANALYSIS_NULLIFY(YTRIP)
!
  TYPE(TRIP_ANALYSIS_t), INTENT(INOUT) :: YTRIP
  REAL(KIND=JPRB) :: ZHOOK_HANDLE
  IF (LHOOK) CALL DR_HOOK("MODD_TRIP_ANALYSIS:TRIP_ANALYSIS_NULLIFY",0,ZHOOK_HANDLE)
!
  NULLIFY(YTRIP%XB)
  NULLIFY(YTRIP%XA)
  NULLIFY(YTRIP%XINFL)
  NULLIFY(YTRIP%XINFL_VAR)
  NULLIFY(YTRIP%XINNOV)
  NULLIFY(YTRIP%XLOCAL)
  NULLIFY(YTRIP%XK)
!
  IF (LHOOK) CALL DR_HOOK("MODD_TRIP_ANALYSIS:TRIP_ANALYSIS_NULLIFY",1,ZHOOK_HANDLE)
END SUBROUTINE TRIP_ANALYSIS_NULLIFY
!
SUBROUTINE TRIP_LOCAL_NULLIFY(YTRIP)
  TYPE(TRIP_LOCAL_t), INTENT(INOUT) :: YTRIP
  REAL(KIND=JPRB) :: ZHOOK_HANDLE
  IF (LHOOK) CALL DR_HOOK("MODD_TRIP_ANALYSIS:TRIP_LOCAL_NULLIFY",0,ZHOOK_HANDLE)
!
  YTRIP%NLEN = 0
!  NULLIFY(YTRIP%NDOWN_STATE)
!  NULLIFY(YTRIP%XCOV)
!
  IF (LHOOK) CALL DR_HOOK("MODD_TRIP_ANALYSIS:TRIP_LOCAL_NULLIFY",1,ZHOOK_HANDLE)
END SUBROUTINE TRIP_LOCAL_NULLIFY
!
END MODULE MODD_TRIP_ANALYSIS

