SUBROUTINE PRINT_STATE(TPST,KLISTING,PGRID,PSTATE)

USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
USE MODD_TRIP_MPI

IMPLICIT NONE

TYPE(TRIP_STATE_t),   INTENT(IN) :: TPST
INTEGER,              INTENT(IN) :: KLISTING
REAL, DIMENSION(:,:), INTENT(IN) :: PGRID
REAL, DIMENSION(:),   INTENT(IN) :: PSTATE

INTEGER :: JPROC,JNUM,JSTATE

WRITE(KLISTING,*) '==============================================='

IF (NRANK==NPIO) THEN
  DO JPROC = 1,NPROC-1
   DO JNUM = 1,4
     JSTATE = TPST%NSTATE_POS(JPROC)+JNUM-1
     WRITE(KLISTING,*) JPROC,TPST%NSTATE_LON(JSTATE),TPST%NSTATE_LAT(JSTATE), &
                       PGRID(TPST%NSTATE_LON(JSTATE),TPST%NSTATE_LAT(JSTATE))
   ENDDO
   DO JNUM = 1,4
     JSTATE = TPST%NSTATE_POS(JPROC)+TPST%NSTATE_LEN(JPROC)-JNUM
     WRITE(KLISTING,*) JPROC,TPST%NSTATE_LON(JSTATE),TPST%NSTATE_LAT(JSTATE), &
                       PGRID(TPST%NSTATE_LON(JSTATE),TPST%NSTATE_LAT(JSTATE))
   ENDDO
  ENDDO
ELSE
  DO JNUM = 1,4
    JSTATE = JNUM
    WRITE(KLISTING,*) NRANK,TPST%NSTATE_LON_P(JSTATE),TPST%NSTATE_LAT_P(JSTATE), &
                      PSTATE(JSTATE)
  ENDDO
  DO JNUM = 1,4
    JSTATE = TPST%NSTATE_LEN(NRANK)-JNUM+1
    WRITE(KLISTING,*) NRANK,TPST%NSTATE_LON_P(JSTATE),TPST%NSTATE_LAT_P(JSTATE), &
                      PSTATE(JSTATE)
  ENDDO
ENDIF

WRITE(KLISTING,*) '==============================================='

END SUBROUTINE PRINT_STATE
