SUBROUTINE TEST_DIAG_WRITE(HVAR,OWRITE)
!
USE MODN_TRIP_RUN,   ONLY : CSELECT
!
USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
CHARACTER(LEN=*),  INTENT(IN)  :: HVAR     ! name of the variable to be written
LOGICAL,           INTENT(OUT) :: OWRITE ! flag for variable to be written
!
INTEGER :: IFIELD,JFIELD
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:TEST_DIAG_WRITE',0,ZHOOK_HANDLE)
!
OWRITE = .TRUE.
IF (SIZE(CSELECT)>0)  THEN
  IFIELD = COUNT(CSELECT /= '            ')
  IF(IFIELD>0)THEN
    OWRITE = .FALSE.
    DO JFIELD = 1,IFIELD
      IF ( TRIM(CSELECT(JFIELD))==TRIM(HVAR) ) THEN
        OWRITE = .TRUE.
      ENDIF
    ENDDO
  ENDIF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:TEST_DIAG_WRITE',1,ZHOOK_HANDLE)
!
END SUBROUTINE TEST_DIAG_WRITE
