!TRP_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!TRP_LIC This is part of the CTRIP software governed by the CeCILL-C licence
!TRP_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!TRP_LIC for details. version 1.
SUBROUTINE TEST_DIAG_WRITE(HVAR,OWRITE)
!
USE MODN_TRIP_RUN,   ONLY : CSELECT
!
USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
CHARACTER(LEN=*),  INTENT(IN)  :: HVAR     ! name of the variable to be written
LOGICAL,           INTENT(OUT) :: OWRITE ! flag for variable to be written
!
INTEGER :: IFIELD,JFIELD
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:TEST_DIAG_WRITE',0,ZHOOK_HANDLE)
!
OWRITE = .FALSE.
IF (SIZE(CSELECT)>0)  THEN
  IFIELD = COUNT(CSELECT /= '            ')
  IF(IFIELD>0)THEN
    OWRITE = .FALSE.
    DO JFIELD = 1,IFIELD
      IF ( TRIM(CSELECT(JFIELD))==TRIM(HVAR) ) THEN
        OWRITE = .TRUE.
      ENDIF
    ENDDO
  ENDIF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:TEST_DIAG_WRITE',1,ZHOOK_HANDLE)
!
END SUBROUTINE TEST_DIAG_WRITE
