!TRP_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!TRP_LIC This is part of the CTRIP software governed by the CeCILL-C licence
!TRP_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!TRP_LIC for details. version 1.
SUBROUTINE TRIP_ALLOC(YDTRIP)
!
USE MODD_SURFEX_TRIP_n, ONLY : TRIP_MODEL_t
!
USE MODD_TRIP, ONLY : TRIP_INIT
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_NULLIFY
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_NULLIFY
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_NULLIFY
USE MODD_TRIP_LAKE, ONLY : TRIP_LAKE_NULLIFY
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE (TRIP_MODEL_t), INTENT (INOUT) :: YDTRIP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("TRIP_ALLOC",0,ZHOOK_HANDLE)
!
CALL TRIP_INIT(YDTRIP%TP)
CALL TRIP_GRID_NULLIFY(YDTRIP%TPG)
CALL TRIP_DIAG_NULLIFY(YDTRIP%TPDG)
CALL TRIP_STATE_NULLIFY(YDTRIP%TPST)
CALL TRIP_LAKE_NULLIFY(YDTRIP%TPLK)
!
IF (LHOOK) CALL DR_HOOK("TRIP_ALLOC",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_ALLOC
