!TRP_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!TRP_LIC This is part of the CTRIP software governed by the CeCILL-C licence
!TRP_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!TRP_LIC for details. version 1.
SUBROUTINE TRIP_DIAG_GATHER(TPLK, TPDG, TPST)
!     ############################################################
!
!!****  *TRIP_DIAG_GATHER*
!!
!!    PURPOSE
!!    -------
!
!     TRIP river routing outputs.
!
!!
!!    AUTHOR
!!    ------
!!      S. Munier
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    28/05/05
!!      T. Guinaldo 04/2020    Add MLake
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
!
USE MODD_TRIP_LAKE,  ONLY : TRIP_LAKE_t
USE MODD_TRIP_DIAG,  ONLY : TRIP_DIAG_t
USE MODD_TRIP_STATE, ONLY : TRIP_STATE_t
!
USE MODN_TRIP,       ONLY : CGROUNDW, CVIT, LFLOOD, CLAKE
USE MODN_TRIP_RUN,   ONLY : LDIAG_MISC
USE MODD_TRIP_OASIS, ONLY : LCPL_LAND
!
USE MODD_TRIP_MPI
!
USE MODE_TRIP_GRID_STATE, ONLY : TRIP_STATE_TO_GRID
USE MODE_TRIP_LAKE, ONLY : TRIP_LAKE_TO_GRID, TRIP_STATE_TO_LAKE
!
USE MODI_WAITING_MPI
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
#ifdef SFX_MPI
INCLUDE "mpif.h"
#endif
!
!*      0.1    declarations of arguments
!
!
TYPE(TRIP_LAKE_t),  INTENT(INOUT) :: TPLK
TYPE(TRIP_DIAG_t),  INTENT(INOUT) :: TPDG
TYPE(TRIP_STATE_t), INTENT(INOUT) :: TPST
!
!*      0.2    declarations of local variables
!
INTEGER :: ISTATE
REAL, DIMENSION(:), ALLOCATABLE   :: ZSTATE
!
INTEGER :: IERR
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_GATHER',0,ZHOOK_HANDLE)
!
CALL WAITING_MPI('TRIP_DIAG_GATHER')
!
IF (NRANK==NPIO) THEN
  ALLOCATE(ZSTATE(TPST%NNSTATE))
ELSE
  ALLOCATE(ZSTATE(0))
ENDIF
ISTATE = TPST%NNSTATE_P
!
CALL MPI_GATHER(TPDG%TDIAG_ST%XSURF_STO,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) THEN
  CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XSURF_STO)
  IF(CLAKE=='MLK')THEN
    CALL TRIP_LAKE_TO_GRID(TPLK%NLAKE_ID_NW,TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XSURF_STO)
    CALL TRIP_STATE_TO_LAKE(TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XLAKE_STO)
  ENDIF
ENDIF
TPDG%TDIAG_ST%XSURF_STO(:) = 0
!
CALL MPI_GATHER(TPDG%TDIAG_ST%XQDIS,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
IF (NRANK==NPIO) THEN
  CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XQDIS)
  IF(CLAKE=='MLK')THEN
    CALL TRIP_LAKE_TO_GRID(TPLK%NLAKE_ID_NW,TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XQDIS)
    CALL TRIP_STATE_TO_LAKE(TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XLAKE_OUT)
  ENDIF
ENDIF
TPDG%TDIAG_ST%XQDIS(:) = 0
!
IF(LDIAG_MISC)THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XQIN,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) THEN
    CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XQIN)
    IF(CLAKE=='MLK')THEN
      CALL TRIP_LAKE_TO_GRID(TPLK%NLAKE_ID_NW,TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XQIN)
      CALL TRIP_STATE_TO_LAKE(TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XLAKE_IN)
    ENDIF
  ENDIF
  TPDG%TDIAG_ST%XQIN(:) = 0
!
ENDIF
!
IF(LCPL_LAND.AND.LDIAG_MISC)THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XRUNOFF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XRUNOFF)
  TPDG%TDIAG_ST%XRUNOFF(:) = 0
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XDRAIN,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XDRAIN)
  TPDG%TDIAG_ST%XDRAIN(:) = 0
!
ENDIF
!
IF(CGROUNDW/='DEF')THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XQGF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XQGF)
  TPDG%TDIAG_ST%XQGF(:) = 0
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XGROUND_STO,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XGROUND_STO)
  TPDG%TDIAG_ST%XGROUND_STO(:) = 0
!
ENDIF
!
IF(CGROUNDW=='DIF')THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XHGROUND,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XHGROUND)
  TPDG%TDIAG_ST%XHGROUND(:) = 0
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XFWTD,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XFWTD)
  TPDG%TDIAG_ST%XFWTD(:) = 0
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XWTD,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XWTD)
  TPDG%TDIAG_ST%XWTD(:) = 0
!
  IF(LDIAG_MISC)THEN
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XQGCELL,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XQGCELL)
    TPDG%TDIAG_ST%XQGCELL(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XHGHS,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XHGHS)
    TPDG%TDIAG_ST%XHGHS(:) = 0
!
  ENDIF
!
ENDIF
!
IF(CVIT=='VAR')THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XVEL,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XVEL)
  TPDG%TDIAG_ST%XVEL(:) = 0
!
ENDIF
!
IF(CVIT=='VAR'.OR.CLAKE=='MLK')THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XHS,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) THEN
    CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XHS)
    IF(CLAKE=='MLK')THEN
      CALL TRIP_LAKE_TO_GRID(TPLK%NLAKE_ID_NW,TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XHS)
      CALL TRIP_STATE_TO_LAKE(TPST%NLAKE_STATE,ZSTATE,TPDG%TDIAG%XLAKE_H)
    ENDIF
  ENDIF
  TPDG%TDIAG_ST%XHS(:) = 0
!
ENDIF
!
IF(LFLOOD)THEN
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XFF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XFF)
  TPDG%TDIAG_ST%XFF(:) = 0
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XFLOOD_STO,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XFLOOD_STO)
  TPDG%TDIAG_ST%XFLOOD_STO(:) = 0
!
  CALL MPI_GATHER(TPDG%TDIAG_ST%XHF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
  IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XHF)
  TPDG%TDIAG_ST%XHF(:) = 0
!
  IF(LDIAG_MISC)THEN
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XSOURCE,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XSOURCE)
    TPDG%TDIAG_ST%XSOURCE(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XQFR,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XQFR)
    TPDG%TDIAG_ST%XQFR(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XQRF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XQRF)
    TPDG%TDIAG_ST%XQRF(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XVFIN,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XVFIN)
    TPDG%TDIAG_ST%XVFIN(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XVFOUT,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XVFOUT)
    TPDG%TDIAG_ST%XVFOUT(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XHSF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XHSF)
    TPDG%TDIAG_ST%XHSF(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XWF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XWF)
    TPDG%TDIAG_ST%XWF(:) = 0
!
    CALL MPI_GATHER(TPDG%TDIAG_ST%XLF,ISTATE,MPI_DOUBLE,ZSTATE,ISTATE,MPI_DOUBLE,NPIO,NCOMM,IERR)
    IF (NRANK==NPIO) CALL TRIP_STATE_TO_GRID(TPST%NSTATE_LON,TPST%NSTATE_LAT,ZSTATE,TPDG%TDIAG%XLF)
    TPDG%TDIAG_ST%XLF(:) = 0
!
  ENDIF
ENDIF
!
DEALLOCATE(ZSTATE)
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_GATHER',1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DIAG_GATHER
