!TRP_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!TRP_LIC This is part of the CTRIP software governed by the CeCILL-C licence
!TRP_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!TRP_LIC for details. version 1.
SUBROUTINE TRIP_DEALLO(YDTRIP)
!
USE MODD_SURFEX_TRIP_n, ONLY : TRIP_MODEL_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODI_DEALLOC_TRIP
!
IMPLICIT NONE
!
TYPE (TRIP_MODEL_t), INTENT(INOUT) :: YDTRIP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("TRIP_DEALLO",0,ZHOOK_HANDLE)
!
 CALL DEALLOC_TRIP
!
IF (LHOOK) CALL DR_HOOK("TRIP_DEALLO",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DEALLO
