!TRP_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!TRP_LIC This is part of the CTRIP software governed by the CeCILL-C licence
!TRP_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!TRP_LIC for details. version 1.
!     #########
      SUBROUTINE TRIP_DIAG_WRITE (TPDG, TPG, &
                                  KLISTING,KLON,KLAT,KLAKE_NUM,KDIAG,PTSTEP_DIAG,OXIOS)
!     ############################################################
!
!!****  *TRIP_DIAG_WRITE*
!!
!!    PURPOSE
!!    -------
!
!     TRIP river routing outputs.
!
!!
!!    AUTHOR
!!    ------
!!      B. Decharme
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    28/05/05
!!      S. Munier   03/2020    CTRIP-12D and parallelization
!!      T. Guinaldo 04/2020    Add MLake
!!      S.Munier    12/2020    selection of output variables
!
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
!
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
!
USE MODN_TRIP,       ONLY : CGROUNDW, CVIT, LFLOOD, CLAKE
USE MODN_TRIP_RUN,   ONLY : LDIAG_MISC
USE MODD_TRIP_OASIS, ONLY : LCPL_LAND
!
USE MODD_TRIP_PAR,   ONLY : XTIME_DIAG
USE MODD_TRIP_MPI,   ONLY : CRANK
!
#ifdef WXIOS
use XIOS
#endif
!
USE MODE_RW_TRIP
USE MODI_TEST_DIAG_WRITE
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
TYPE(TRIP_DIAG_t), INTENT(INOUT) :: TPDG
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
!
INTEGER, INTENT(IN)             :: KLISTING
INTEGER, INTENT(IN)             :: KLON
INTEGER, INTENT(IN)             :: KLAT
INTEGER, INTENT(IN)             :: KLAKE_NUM
INTEGER, INTENT(IN)             :: KDIAG
REAL,    INTENT(IN)             :: PTSTEP_DIAG
LOGICAL, INTENT(IN)             :: OXIOS
!
!*      0.2    declarations of local variables
!
CHARACTER(LEN=19), PARAMETER         :: YDIAG  = 'TRIP_DIAG.nc'
CHARACTER(LEN=50)                    :: YFILE
CHARACTER(LEN=10)                    :: YVNAME
!
REAL,   DIMENSION(KLON,KLAT)         :: ZWRITE
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_VEL
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_FLD
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_GW
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_LAKE
REAL,   DIMENSION(KLAKE_NUM)         :: ZWRITE_LAKE
LOGICAL,DIMENSION(KLAKE_NUM)         :: LMASK_LAKE_1D
!
INTEGER :: ITNUM, ITVAL
LOGICAL :: GWRITE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE',0,ZHOOK_HANDLE)
!
! * Define masks
!
LMASK(:,:) = TPG%GMASK(:,:)
LMASK_VEL(:,:) = .FALSE.
IF(CVIT=='VAR') LMASK_VEL(:,:) = TPG%GMASK_VEL(:,:)
LMASK_FLD(:,:) = .FALSE.
IF(LFLOOD) LMASK_FLD(:,:) = TPG%GMASK_FLD(:,:)
LMASK_GW(:,:) = .FALSE.
IF(CGROUNDW/='DEF') LMASK_GW(:,:) = TPG%GMASK_GW(:,:)
LMASK_LAKE(:,:) = .FALSE.
IF(CLAKE=='MLK') LMASK_LAKE(:,:) = TPG%GMASK_LAKE_NW(:,:)
LMASK_LAKE_1D(:) = .FALSE.
IF(CLAKE=='MLK') LMASK_LAKE_1D(:) = .TRUE.
!
!-------------------------------------------------------------------------------
!outputs
!-------------------------------------------------------------------------------
!
! * Recup diag file
!
YFILE = YDIAG
!
! * Time attribut
!
ITNUM = KDIAG
!
IF (OXIOS) THEN
#ifdef WXIOS
  CALL XIOS_UPDATE_CALENDAR(KDIAG)
#endif
  ITVAL = 0
ELSE
  ITVAL = (KDIAG-1)*INT(PTSTEP_DIAG/XTIME_DIAG)
ENDIF
!
! * Store output in diag file
!
YVNAME = 'SURF_STO'
CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
IF(GWRITE)THEN
  ZWRITE = TPDG%TDIAG%XSURF_STO / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
ENDIF
CALL CUM_DIAG(TPDG%TDIAG%XSURF_STO,TPDG%TDIAG_RUN%XSURF_STO)
!
YVNAME = 'QDIS'
CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
IF(GWRITE)THEN
  ZWRITE = TPDG%TDIAG%XQDIS / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
ENDIF
CALL CUM_DIAG(TPDG%TDIAG%XQDIS,TPDG%TDIAG_RUN%XQDIS)
!
IF(LDIAG_MISC)THEN
  YVNAME = 'QSIN'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XQIN / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XQIN,TPDG%TDIAG_RUN%XQIN)
ENDIF
!
IF(LCPL_LAND.AND.LDIAG_MISC)THEN
! kg/m2 (can be used to force the model offline)
  YVNAME = 'RUNOFF'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XRUNOFF
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XRUNOFF,TPDG%TDIAG_RUN%XRUNOFF)
! kg/m2 (can be used to force the model offline)
  YVNAME = 'DRAIN'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XDRAIN
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XDRAIN,TPDG%TDIAG_RUN%XDRAIN)
!
ENDIF
!
IF(CGROUNDW/='DEF')THEN
!
  YVNAME = 'QGF'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XQGF / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XQGF,TPDG%TDIAG_RUN%XQGF)
!
  YVNAME = 'GROUND_STO'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XGROUND_STO / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XGROUND_STO,TPDG%TDIAG_RUN%XGROUND_STO)
!
ENDIF
!
IF(CGROUNDW=='DIF')THEN
!
  YVNAME = 'HGROUND'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XHGROUND / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XHGROUND,TPDG%TDIAG_RUN%XHGROUND)
!
  YVNAME = 'FWTD'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XFWTD / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XFWTD,TPDG%TDIAG_RUN%XFWTD)
!
  YVNAME = 'WTD'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XWTD / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XWTD,TPDG%TDIAG_RUN%XWTD)
!
  IF(LDIAG_MISC)THEN
!
    YVNAME = 'QGCELL'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XQGCELL / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XQGCELL,TPDG%TDIAG_RUN%XQGCELL)
!
    YVNAME = 'HGHRIV'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XHGHS / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XHGHS,TPDG%TDIAG_RUN%XHGHS)
!
  ENDIF
!
ENDIF
!
IF(CVIT=='VAR')THEN
!
  YVNAME = 'VEL'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XVEL / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_VEL,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XVEL,TPDG%TDIAG_RUN%XVEL)
!
ENDIF
!
IF(CVIT=='VAR'.OR.CLAKE=='MLK')THEN
!
  YVNAME = 'HSTREAM'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XHS / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_VEL.OR.LMASK_LAKE,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XHS,TPDG%TDIAG_RUN%XHS)
!
ENDIF
!
IF(LFLOOD)THEN
!
  YVNAME = 'FFLOOD'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XFF / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XFF,TPDG%TDIAG_RUN%XFF)
!
  YVNAME = 'FLOOD_STO'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XFLOOD_STO / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XFLOOD_STO,TPDG%TDIAG_RUN%XFLOOD_STO)
!
  YVNAME = 'HFLOOD'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE = TPDG%TDIAG%XHF / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG(TPDG%TDIAG%XHF,TPDG%TDIAG_RUN%XHF)
!
  IF(LDIAG_MISC)THEN
!
! kg/m2 (can be used to force the model offline)
    YVNAME = 'FSOURCE'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XSOURCE
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XSOURCE,TPDG%TDIAG_RUN%XSOURCE)
!
! kg/m2/s
    YVNAME = 'QFR'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XQFR / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XQFR,TPDG%TDIAG_RUN%XQFR)
!
    YVNAME = 'QRF'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XQRF / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XQRF,TPDG%TDIAG_RUN%XQRF)
!
    YVNAME = 'VFIN'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XVFIN / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XVFIN,TPDG%TDIAG_RUN%XVFIN)
!
    YVNAME = 'VFOUT'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XVFOUT / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XVFOUT,TPDG%TDIAG_RUN%XVFOUT)
!
    YVNAME = 'HSF'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XHSF / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XHSF,TPDG%TDIAG_RUN%XHSF)
!
    YVNAME = 'WF'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XWF / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XWF,TPDG%TDIAG_RUN%XWF)
!
    YVNAME = 'LF'
    CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
    IF(GWRITE)THEN
      ZWRITE = TPDG%TDIAG%XLF / PTSTEP_DIAG
      CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    ENDIF
    CALL CUM_DIAG(TPDG%TDIAG%XLF,TPDG%TDIAG_RUN%XLF)
!
  ENDIF
!
ENDIF
!
IF(CLAKE=='MLK')THEN
!
  YVNAME = 'LAKE_STO'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE_LAKE = TPDG%TDIAG%XLAKE_STO / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_LAKE_1D,ZWRITE_LAKE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG_1D(TPDG%TDIAG%XLAKE_STO,TPDG%TDIAG_RUN%XLAKE_STO)
!
  YVNAME = 'LAKE_OUT'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE_LAKE = TPDG%TDIAG%XLAKE_OUT / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_LAKE_1D,ZWRITE_LAKE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG_1D(TPDG%TDIAG%XLAKE_OUT,TPDG%TDIAG_RUN%XLAKE_OUT)
!
  YVNAME = 'LAKE_IN'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE_LAKE = TPDG%TDIAG%XLAKE_IN / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_LAKE_1D,ZWRITE_LAKE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG_1D(TPDG%TDIAG%XLAKE_IN,TPDG%TDIAG_RUN%XLAKE_IN)
!
  YVNAME = 'LAKE_H'
  CALL TEST_DIAG_WRITE(YVNAME,GWRITE)
  IF(GWRITE)THEN
    ZWRITE_LAKE = TPDG%TDIAG%XLAKE_H / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_LAKE_1D,ZWRITE_LAKE,ITNUM,ITVAL,OXIOS=OXIOS)
  ENDIF
  CALL CUM_DIAG_1D(TPDG%TDIAG%XLAKE_H,TPDG%TDIAG_RUN%XLAKE_H)
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
 CONTAINS
!-------------------------------------------------------------------------------
!
SUBROUTINE CUM_DIAG(PDIAG,PRUN)
!
IMPLICIT NONE
!
REAL, DIMENSION(:,:),INTENT(INOUT) :: PDIAG
REAL, DIMENSION(:,:),INTENT(INOUT) :: PRUN
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:CUM_DIAG',0,ZHOOK_HANDLE)
!
PRUN(:,:) = PRUN(:,:) + PDIAG(:,:)
!
PDIAG(:,:) = 0.0
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:CUM_DIAG',1,ZHOOK_HANDLE)
!
END SUBROUTINE CUM_DIAG
!
!-------------------------------------------------------------------------------
!
SUBROUTINE CUM_DIAG_1D(PDIAG,PRUN)
!
IMPLICIT NONE
!
REAL, DIMENSION(:),INTENT(INOUT) :: PDIAG
REAL, DIMENSION(:),INTENT(INOUT) :: PRUN
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:CUM_DIAG_1D',0,ZHOOK_HANDLE)
!
PRUN(:) = PRUN(:) + PDIAG(:)
!
PDIAG(:) = 0.0
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:CUM_DIAG_1D',1,ZHOOK_HANDLE)
!
END SUBROUTINE CUM_DIAG_1D
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE TRIP_DIAG_WRITE
